### ISSUE TITLE
Guide for using bot in Heroku 

### ISSUE THREAD

**Issue by m33Lucky** [BitBotFactory/poloniexlendingbot#109]
Can some make a detailed guide to use bot on heroku

**Comment by mefjiu** [comment]
Also I tried to fire up there and did not work.

**Comment by laxdog** [comment]
@m33Lucky Why don't you have a go at it and someone can help you through it?

**Comment by ckcollab** [comment]
I was also interested in this! I could do this work (could even one-click-deploy), but I'd want to rip out a few pieces and abstract/decouple them more... is this already being done in another branch or is it on the roadmap?

**Comment by laxdog** [comment]
This is being done to an extent as part of the unit test work. 

There's a few other things I was planning on doing around it too, if it'll help with this though I can expedite it.

Was there something in particular @ckcollab you were thinking of?

**Comment by ckcollab** [comment]
Configuration is a big one, it's tied to this file and class, where it should probably be coming from environment variables... ideally... but it is *so nice* how easy it is right now to get going if you don't know what environment variables are...

I would propose switching to yaml files (nicer to edit as a human) and mapping all of the same settings to env vars. Completely get rid of the settings class and replace it with a few lines loading yaml if it's there, loading default if not, prompting for key/secret, save yaml file for them, and then go on like normal.

Then with both yaml + env vars handled we have the nicest "human editable" format as well as easy server setup (Heroku, docker `.env` files, etc.).

Does that sound like too much work for too little benefit? I've already done a bit of this but it's kind of janky and I'm very nervous to mess with this stuff :)

**Comment by HostFat** [comment]
I'm also interested on this :)

**Comment by HostFat** [comment]
Can the dev add something like an official bitcoin address to donate for the bounty of this feature?

**Comment by ckcollab** [comment]
I would say this shouldn't go on heroku, free version at least. Requires significant rewriting to work there. Wsgi server, task queue, etc etc etc

Can be done, much simpler otherwise.

**Comment by ckcollab** [comment]
And to be clear I will do this if you want but it'll cost probably 10 billable hours, at least.

**Comment by HostFat** [comment]
I'm not sure if this info can help to limit the work required:

https://devcenter.heroku.com/articles/free-dyno-hours

By verifying a credit/debit card, free dyno hours are the 1000.

and

"Worker-only Free dynos do not sleep since they do not respond to web requests. Be mindful of this as they may run 24/7 and consume from your pool of hours."

**Comment by ckcollab** [comment]
Right, like I said, it could work on there but running 24/7 won't work. That's why you need a task queue or something to spin up every-so-often.

**Comment by HostFat** [comment]
Well, I'm not sure how the free dyno hours are used and calculated, but if they are "hours", 1000 hours **every-month**, "for only 1 app", they are a lot :) 

It shouldn't need the task queue system.

**Comment by ckcollab** [comment]
> It shouldn't need the task queue system.

It may not need a task queue, but it can't run 24/7, and this is meant to run 24/7. 

Feel free to write it if you have the solution in mind ;)

**Comment by HostFat** [comment]
Why it can't run 24/7 ?

The larger month is of 31 days, so 744 hours ...

**Comment by ckcollab** [comment]
Because it will go to sleep after 30 min idle... you need it to stay awake and continue processing on its own, you may be able to easily do this with a Heroku scheduler of some sort (task queue). Not to mention, you need to setup WSGI (I believe) among other things to make this run on Heroku. It just uses `SimpleHTTPServer` now not gunicorn/uwsgi/etc.

**Comment by HostFat** [comment]
Ok.

And what does it mean with this?
"Worker-only Free dynos do not sleep since they do not respond to web requests."

Can the bot be set as "Worker-only"?

**Comment by ckcollab** [comment]
> Can the bot be set as "Worker-only"?


...try it out :)

**Comment by ckcollab** [comment]
Oh! Also, Heroku filesystem is ephemeral so you'll have to get `default.cfg` generated somewhere in there. Can probably store it on S3 and download it in a custom buildpack.

**Comment by laxdog** [comment]
Closing, this isn't happening.
