### ISSUE TITLE
Plugin support?

### ISSUE THREAD

**Issue by Evanito** [BitBotFactory/poloniexlendingbot#224]
I am considering adding support for third-party, not necessarily-approved-by-us plugins.
They would be placed in a `Plugins/` folder which contain a folder for each plugin. 
The name of the folder would be the name of the python file which would be run, plugins would be able to choose at which point they are run through their own configurations, including multiple locations. In addition, allow async plugins.
```
The main loop:

<Plugin run location 1>
Data.update_conversion_rates()
Lending.transfer_balances()
<Plugin run location 2>
Lending.cancel_all()
<Plugin run location 3>
Lending.lend_all()
<Plugin run location 4>
log.refreshStatus()
log.persistStatus()
sys.stdout.flush()
<Plugin run location 5>
time.sleep()
```

Any thoughts?

**Comment by laxdog** [comment]
Could be quite useful, yea. The actual calls would need to be inside each of the modules to get access to all the variables.

It would actually be great if all the functions were wrapped with decorators that you could hook into with plugins. Well, maybe all of them is overkill, but some of the more interesting ones.

Have there been many things you have thought would be good as a plugin though? 
I guess it's more of a "if you build it, they will come".

**Comment by rnevet** [comment]
IMO stability, analysis and basic bot behavior are still lacking, and this isn't a defined need.

**Comment by laxdog** [comment]
On purely priority, there are definitely other things that could be fixed...

**Comment by rnevet** [comment]
@Evanito I think I implemented this more or less in the AccountAnalysis :)

**Comment by Evanito** [comment]
Closing due to implemented
