### ISSUE TITLE
Discussion : Golden cross analysis

### ISSUE THREAD

**Issue by laxdog** [BitBotFactory/poloniexlendingbot#230]
I don't have the time to start work on this at the minute, but I was thinking of implementing a golden cross type signal for lending to start. We'd still keep the min daily rate, lendingstyle % and any other safe guards in place. 

A quick explanation of golden cross is basically that you check two moving averages, a short time period and a longer time period. When the short one crosses the longer one, you know that the market is performing above average, so it's time to lend. (Strictly there's more to it than that, but that's the general idea)

There has already been some work done in the MarketAnalysis module to keep historical data, so this could be leveraged for this method too. It would be good to see that module being built out and added to with different analysis methods.

Though maybe there needs to be some ground work done on the bot first as it's getting quite complex. So the unit tests that have been talked about (at least a framework for them) and a cleaner / more extensible config (I'd like to have support for nested configs basically).

**Comment by Evanito** [comment]
I love the idea of utilizing a golden cross system. I can modify the ``get_rate_list()`` function to also accept a number of days, where it will return a list with rates under that day age. From there, you can find the averages and compare. But if short-term is higher than long-term, then what?

Raanan and I agree that eventually we will need to completely rewrite the config to make it more sustainable and organized. We wanted to do this all at once so that configs don't break every other update.

**Comment by laxdog** [comment]
OK, you want to leave this open as a placeholder then and we'll work at getting the rest of that crap sorted out?

I'll have a look at unit tests first I guess. 

I really wish this was all in python 3 too, but that's a pipe dream at the minute. 

However, I'd urge people to try and write stuff that's compatible if they can.

**Comment by rnevet** [comment]
My priorities are:
1. Unit testing, we've been breaking the bot basic functionality left and right while trying to add feature.
2. Reporting, we need to be able to compare performance - it doesn't make sense to implement algorithms when you can't compare. Things like accepted loan rates, loaned rate and earning over time.
3. Algorithms, I actually think there is a potential in analysis of the exchange rate, it is quite clear that a big raise leads people to do shorts on the currency and rates go up - maybe we can optimize how loans are spread at such a time, also the other way around - after a dip loan rates drop fast.

Can we write the unit test so they are python 3 compatible?

**Comment by laxdog** [comment]
Been doing a bit of analysis on this and it looks like it'll work quite well. This is a graph I made of 1 min (blue), 5 min (orange) and 1 hour (grey) moving averages of the lending rates on BTC. 

You can clearly see where each of the averages cross. I'll do a bit more messing with the numbers at some stage, but I think for a start when the 5 minute crosses the 1 hour would be a pretty good signal to lend.

So basically, if the 5 minute average is below the 1 hour average, don't lend the coin. If it's above, give back a rate suggestion of whatever the average is currently.

The data I used was just the top rate of the lending book, it might be useful to get a bit more information to analyse as I'm not doing any weighting. That said, since they're already moving averages, it's probably fine.

<img width="1012" alt="screen shot 2017-03-10 at 1 11 10 pm" src="https://cloud.githubusercontent.com/assets/794502/23796679/1e14ea92-0594-11e7-9470-d3e85aa24755.png">

We again come back to the question of how to actually test the efficacy these new algos, which I can't really come up with a good solution for. There was a mention of accepted loan rates before, which we could use in conjunction with the loan offers maybe. But it'll always be lower. We really would need the rates that have been accepted already, which we don't have access too. 

I'd thought before about recording all the loan that are displayed and trying to use that, but it's inaccurate as you don't know if they've been accepted or cancelled when the disappear. 

Anyway.... I'm going to finish the tests on MarketAnalysis, then put in a simple version of this to test. The code isn't actually that complicated (I think).

**Comment by laxdog** [comment]
OK, so I've done some testing with a simple implementation, it's running on my prod setup at the minute. I'm using 5 minutes and 1 hour as my short and long average periods.

It looks good so far, I've basically hooked into the cur_min_daily_rate variable, the same way the percentile calculation does. It's definitely giving a more accurate representation of what the market is doing and from watching I'm happy enough with how it's performing. 

I'll  leave it running for a while and watch how it's getting on. From what I can see so far, it's much better to run it at a shorter interval, so it connects every second and tries to make an offer. I've seen it sneak in quite a few rates that probably wouldn't happen if they were left in the book for ages. I think that's going to be the biggest benefit of this, basically sniping loans.

I'm half tempted not to put this in now in case everyone steals the best deals! :)

Still need to do loads of config and docs before I can raise a PR. 

I've been working from the unit test branch too, so I need to get that merged first too.

**Comment by rnevet** [comment]
I'll finish the account value feature and then review and test the unit testing branch.

**Comment by laxdog** [comment]
Great, thanks. No major rush, it'll take me a while to get the other stuff done anyway. Though I can raise the PR with what I've got as soon as that's in.

**Comment by laxdog** [comment]
Working being carried out here: https://github.com/Mikadily/poloniexlendingbot/pull/292

**Comment by laxdog** [comment]
Closing this, follow the PR https://github.com/BitBotFactory/poloniexlendingbot/pull/292 or tracker https://github.com/BitBotFactory/poloniexlendingbot/issues/315 for updates.

**Comment by msmyers** [comment]
@laxdog I loved your analysis. How can I get in contact with you? Could you shoot me an email at  michael@coinme.com ?

**Comment by Evanito** [comment]
@msmyers You can join us in the slack channel (Invitation link can be found in the readme file.) There you can chat with all the lead developers as well as members of the community.
