### ISSUE TITLE
Add current order rate to show why we are not lending

### ISSUE THREAD

**Issue by noonway** [BitBotFactory/poloniexlendingbot#231]
Hey, all... I've made a change to modules/Lending.py to inform exactly what the current rate is as to why the bot is not lending.

This line:

`log.log("Not lending {:s} due to rate below {:.4f}%".format(active_cur,(cur_min_daily_rate * 100)))`

Changes to this:

`log.log("Not lending {:s} due to rate of {:.6f}% below {:.4f}%".format(active_cur,(Decimal(orders['rates'][i]) * 100),(cur_min_daily_rate * 100)))`

I made the current order rate 6 decimal places because when I made it 4 decimal places like the cur_min_daily_rate there was some overlap that made it hard to tell exactly why it wasn't lending.  Six decimal places seem to do the trick.

I am a complete GitHub newb so if you guys think its useful, please add to a future commit.  If not, I'll continue to add this line back in on my side if I need to make a pull on modules/Lending.py  👍

**Comment by noonway** [comment]
Example output:

2017-02-10 13:34:39 Not lending BTC due to rate of 0.019800% below 0.0238%
2017-02-10 13:29:26 Not lending BTC due to rate of 0.019600% below 0.0238%

**Comment by rnevet** [comment]
definitely an improvement, I have an idea how to calculate the display precision dynamically. similar to how prettyPrint is implemented in the javascript. I'll give it a go. :)

**Comment by kryztoval** [comment]
Funny, I made almost the exact same change, but I added the amount not being lent.

2017-03-16 12:18:57 Not lending 9.36377915 DASH due to 0.1947% rate is below 0.1998%
2017-03-16 12:18:23 Not lending 9.36377915 DASH due to 0.1947% rate is below 0.1998%

**Comment by rnevet** [comment]
this has been implemented
