### ISSUE TITLE
gapbottom

### ISSUE THREAD

**Issue by zkSNARK** [BitBotFactory/poloniexlendingbot#268]
gapbottom doesn't seem to be having any impact in the latest version.  All my loans are being priced at a 0 gap.  Running on linux python 2.7.

**Comment by rnevet** [comment]
What are you using for gapbottom value?

**Comment by zkSNARK** [comment]
I have tested with a bunch of different values starting from the default all the way to 10%.  Nothing I have done seems to make a difference.

**Comment by rnevet** [comment]
My current value is 3000, which is 3x the amount of coins I have.

**Comment by zkSNARK** [comment]
rnevet, I think you might be confused.  Gapbottom should be controlling your minimum lending rate compared to the rest of the market, and specifically compared to the current lowest costing loan.  The idea is that it will increase your loan price past a certain amount (percentage?) of the cheapest loans in order to get you a better price.

**Comment by rnevet** [comment]
I'm not confused, I suggest you look into this issue:
https://github.com/Mikadily/poloniexlendingbot/issues/269
See how gapbottom is implemented at the moment.

**Comment by zkSNARK** [comment]
I'm the one who is confused then.  I still don't understand what you mean.  Why are the default values set where they are if they seem to have no effect?  Or are you saying that the effect is dependent on the number of coins you have?  I don't believe this was the case in the past and it doesn't make sense that the behavior would depend on the number of coins you have.
