### ISSUE TITLE
Feature request gapbottom and gaptop by nominal units count, not by % of the portfolio

### ISSUE THREAD

**Issue by izischein** [BitBotFactory/poloniexlendingbot#269]
gapbottom and gaptop variable are defined how far into the lending book (in percent of the balance for the respective coin) the bot will go

the % of the balance is not so relevant, as my balance can be changed from time to time, and as I think that the strategy of where to place my lending order has nothing to do with my personal balance.

I prefer to always place my order in depth of 60 to 80 btc inside the lending book, 1000 to 1200 eth inside the lending book, etc…

Can you please add variables which are similar to gapbottom and gaptop, but defined by nominal unit numbers, not % of the balance? That way, I don't need to change the config file every time I withdraw or deposit money to/from the lending account.

In the example I gave, If I want depth of 60-80 btc for lending bitcoin and depth of 1000-1200 eth for lending ether, I should config the suggested 

nominal_gapbottom 	= 60,
nominal_gaptop		= 80,

and 1000, 1200 in the eth respected coinconfig fields.

Of course, it is recommended to add boolean variable to define if the bot will use the % gapbottom, gaptop variables or the nomninal variable.

**Comment by Fornax96** [comment]
I was about to make a feature request about this myself, I currently have my gapbottom and gaptop set to 50000 and 100000, but I find that it often still gets caught up in dust orders, which is very annoying. An option to set the values directly in bitcoins would be a great improvement.

**Comment by rnevet** [comment]
I agree there is an issue here. However considering that the bot loans other coins as well so nominal values won't solve the problem. 

I was thinking more of a solution in the lines of calculating dust level automatically from the offers, but I don't have a good algorithm yet. Suggestions are welcome.

**Comment by izischein** [comment]
the bot has a coinconfig section which you can give any coin different configuration, so loan of multiple coin is not an issue. I also suggested to add boolean variable to define if the bot will use the % gapbottom, gaptop variables as before or the nomninal variable.

**Comment by laxdog** [comment]
Adding the config per coin is non-trivial. We have the means to add the config easily enough, it's the implementation that needs changed.

Another solution is to change it to a percentage of the total volume in the book, but that requires a lot of data transmitted for each loan. 

A simpler solution for the mean time is to add a mechanism to skip dust offers as mentioned.

The market analysis changes I've been working on recently help with this by allowing a MACD type calculation and then creating a loan that is X% above the best rate once the short term moving average crosses the long term moving average. 

I think the issue with a lot of these config options is that people are trying to create strategies from them, when really we just need to create proper strategies in the bot.

**Comment by Evanito** [comment]
This is being implemented in #343 
So please test out that branch and tell me if you have any tweaks you would like made!
