### ISSUE TITLE
List indices must be integers, not Decimal

### ISSUE THREAD

**Issue by kryogenic** [BitBotFactory/poloniexlendingbot#284]
Not really sure what caused this, just that it happened when I changed my `spreadlend` from 7 to 20. Will update if it happens again.

```
list indices must be integers, not Decimal
-------
Traceback (most recent call last):
  File "lendingbot.py", line 75, in <module>
    Lending.lend_all()
  File "/home/kale/poloniexlendingbot/modules/Lending.py", line 200, in lend_all
    usable_currencies += lend_cur(cur, total_lended, lending_balances)
  File "/home/kale/poloniexlendingbot/modules/Lending.py", line 324, in lend_cur
    orders = construct_orders(active_cur, active_bal)  # Construct all the potential orders
  File "/home/kale/poloniexlendingbot/modules/Lending.py", line 288, in construct_orders
    order_rates[rate] = max_daily_rate
TypeError: list indices must be integers, not Decimal
```

**Comment by laxdog** [comment]
I've had this happen before when Polo is not accepting all connections properly. Wasn't sure how to reproduce, so I didn't look too far into it.

**Comment by chano08** [comment]
had this happen also, not sure if I'm doing it right, but here's how i seem to fix it.

https://github.com/chano08/poloniexlendingbot/commit/4f2b8de7b5ad0cc0de04f87a01d1ca05c0c44d7e

instead of using the order rate values, i used indexes.

**Comment by laxdog** [comment]
That may work, but I think we need to solve the problem further up. We shouldn't be continuing if we get garbage data from Polo.

**Comment by rnevet** [comment]
This was fixed here:
https://github.com/BitBotFactory/poloniexlendingbot/commit/d4538ed670c35b39f4cc5d860b3147c0a6e41131
