### ISSUE TITLE
How to run bot on Pythonanywhere

### ISSUE THREAD

**Issue by Willstar44** [BitBotFactory/poloniexlendingbot#287]
https://poloniexlendingbot.readthedocs.io/en/latest/installation.html#installing-on-pythonanywhere-com
So I have copied all my file over, even every  file  inside every  folder 
Move to console create a new with python /home/<username>/poloniexlendingbot/lendingbot.py

But it not running for me? 

I it possible to download the file from the bash console? Could we set step buy step guide please. 

Files I have added 

 .gitignore
2017-03-30 07:03	87 bytes
 CONTRIBUTING.md 2017-03-30 07:09	3.4 KB
 Configuration.py 2017-03-30 07:05	6.8 KB
 Configuration.pyc  		2017-03-30 07:05	5.9 KB
 ConsoleUtils.py  2017-03-30 07:05	2.5 KB
 ConsoleUtils.pyc 2017-03-30 07:05	2.9 KB
 Data.py  2017-03-30 07:05	5.8 KB
 Data.pyc 2017-03-30 07:06	5.5 KB
 LICENSE 2017-03-30 07:02	1.1 KB
 Lending.py 2017-03-30 07:06	13.7 KB
 Lending.pyc 		2017-03-30 07:06	11.3 KB
 Logger.py 2017-03-30 07:06	4.8 KB
 Logger.pyc  		2017-03-30 07:06	7.9 KB
 Makefile 2017-03-30 07:08	7.5 KB
 MarketAnalysis.py 2017-03-30 07:06	5.7 KB
 MaxToLend.py 2017-03-30 07:06	2.8 KB
 MaxToLend.pyc  		2017-03-30 07:06	2.2 KB
 Notify.py 2017-03-30 07:07	2.9 KB
 Notify.pyc  		2017-03-30 07:07	3.6 KB
 PULL_REQUEST_TEMPLATE.md 2017-03-30 07:09	1.8 KB
 Poloniex.py 2017-03-30 07:07	9.9 KB
 Poloniex.pyc  		2017-03-30 07:07	8.7 KB
 README.md  2017-03-30 07:04	805 bytes
 RingBuffer.py 2017-03-30 07:07	1.1 KB
 RingBuffer.pyc  		2017-03-30 07:07	1.6 KB
 WebServer.py 2017-03-30 07:08	2.8 KB
 __init__.py 2017-03-30 07:04	113 bytes
 __init__.pyc  		2017-03-30 07:04	157 bytes
 conf.py 2017-03-30 07:09	9.8 KB
 configuration.rst 2017-03-30 07:09	23.7 KB
 contributing.rst 2017-03-30 07:08	5.1 KB
 default.cfg 2017-03-30 07:03	6.7 KB
 default.cfg.example 2017-03-30 07:02	6.4 KB
 icon.ico  		2017-03-30 07:03	236.5 KB
 icon192.png  		2017-03-30 07:04	8.1 KB
 icon32.png 		2017-03-30 07:04	1.4 KB
 icon384.png 		2017-03-30 07:04	18.0 KB
 icon48.png 		2017-03-30 07:03	2.0 KB
 index.rst 2017-03-30 07:08	421 bytes
 installation.rst2017-03-30 07:08	5.4 KB
 ios_splash.png  		2017-03-30 07:04	13.7 KB
 lendingbot.html 2017-03-30 07:03	3.6 KB
 lendingbot.js 2017-03-30 07:03	13.5 KB
 lendingbot.py 2017-03-30 07:02	4.9 KB
 make.bat 2017-03-30 07:08	7.3 KB
 manifest.json 2017-03-30 07:03	433 bytes
 readme.txt 2017-03-30 07:08	212 bytes
 test_MarketAnalysis.py 2017-03-30 07:04	3.8 KB

**Comment by rnevet** [comment]
"But it not running for me" is not really a useful error description.

**Comment by Willstar44** [comment]
Sorry I am getting :
 bash: billyboy402: No such file or directory
Console closed.

**Comment by rnevet** [comment]
Try changing to the bot directory and running it simply with 'python lendingbot.py'

**Comment by laxdog** [comment]
@Willstar44 Please follow the new installation instructions for python anywhere and let us know then if you have an issues. http://poloniexlendingbot.readthedocs.io/en/latest/installation.html#installing-on-pythonanywhere-com

Closing as the method for installation is no longer recommended.
