### ISSUE TITLE
irc announcer

### ISSUE THREAD

**Issue by redline187** [BitBotFactory/poloniexlendingbot#303]
would be nice some irc announcer notification

**Comment by laxdog** [comment]
Should be easy enough to add in to the notifications. We can use the python socket library and keep it all pure python. We should probably default to SSL, but allow it to be turned off. 

There's a good example here:
http://archive.oreilly.com/pub/h/1968

I'll have a look at it when I get time.

**Comment by laxdog** [comment]
Started the work on irc_announcer_issue_303 branch. 

The code to send to IRC works, just need to add configs for it.

**Comment by laxdog** [comment]
Could you test this quickly @redline187 ?
