### ISSUE TITLE
Issue Running Script in PythonAnywhere

### ISSUE THREAD

**Issue by GordanGeeko** [BitBotFactory/poloniexlendingbot#313]
Hi there,

I get the following error when I try to bash the script in PythonAnywhere:
```
>>> python lendingbot.py
  File "<stdin>", line 1
    python lendingbot.py
                    ^
SyntaxError: invalid syntax
>>> 
```

Can't figure out why. I can run it via clicking on it in Windows fine, and I'm using the same default.cfg file. Any help or assistance is appreciated.

**Comment by laxdog** [comment]
It looks like you started a python shell to try and start the bot, you need to start a bash shell and run to that command.

**Comment by GordanGeeko** [comment]
Hi laxdog,

I was using Bash for that. Is there a different command I need to input to Bash to get it to run? 

Thanks,

**Comment by rnevet** [comment]
Try simple CMD then instead.

**Comment by rnevet** [comment]
@GordanGeeko resolved?

**Comment by GordanGeeko** [comment]
I don't have an option to run CMD on PythonAnywhere.com, when I tried running an equivalent in my Windows, it wouldn't work. I could run the python file in Windows, though.

**Comment by rnevet** [comment]
Sorry, didn't notice you were referring to PythonAnywhere -> not CMD. :)

I suggest you ask for help on our gitter chat, I know some people running the bot on PythonAnywhere.

**Comment by laxdog** [comment]
@GordanGeeko The docs have been update with the new recommended method for installing on python anywhere. 

Please try them http://poloniexlendingbot.readthedocs.io/en/latest/installation.html#installing-on-pythonanywhere-com

Closing this issue as it's no longer valid for current installation methods.
