### ISSUE TITLE
Bugs / required features for new market analysis module

### ISSUE THREAD

**Issue by laxdog** [BitBotFactory/poloniexlendingbot#315]
Keeping a track of these here so I can work through them:

1) During the initial data collection interval the bot lends as if MA it turned off. This is undesirable for me (and probably most people), so needs a method to stop it and needs to be configurable
2) Still getting lots of `OperationalError: database is locked`. Full traceback:
```
Traceback (most recent call last):
  File "/home/dog/MACD_testing/modules/MarketAnalysis.py", line 91, in update_market_thread
    self.update_market(db_con, cur, self.recorded_levels)
  File "/home/dog/MACD_testing/modules/MarketAnalysis.py", line 122, in update_market
    db_con.execute(insert_sql)
```
3) Had a too many open files error, not sure how it was caused yet:
```
Error in MarketAnalysis: <urlopen error [Errno 24] Too many open files> Requesting returnLoanOrders
Traceback (most recent call last):
  File "/home/dog/MACD_testing/modules/MarketAnalysis.py", line 91, in update_market_thread
    self.update_market(db_con, cur, self.recorded_levels)
  File "/home/dog/MACD_testing/modules/MarketAnalysis.py", line 109, in update_market
    raw_data = self.api.return_loan_orders(cur, levels)['offers']
  File "/home/dog/MACD_testing/modules/Poloniex.py", line 242, in return_loan_orders
    return self.api_query('returnLoanOrders', {"currency": currency, "limit": limit})
  File "/home/dog/MACD_testing/modules/Poloniex.py", line 40, in new_method
    return method(self, *arg, **kws)
  File "/home/dog/MACD_testing/modules/Poloniex.py", line 108, in api_query
    ret = urllib2.urlopen(urllib2.Request(req_url))
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
```
4) Old data isn't being deleted (code for it locks the DB continually)
5) All config values are hardcoded
6) A historical source of rates would greatly improve start up speed. Anyone know of somewhere storing rates that we could query?
7) Current rate used is not weighted, so dust offers can still skew the price. I've a column in the DB for percentile, and old code to add to it. Just need to pull that in. 
8) Averages are calculated with pandas.rolling_mean, we don't need this any more and it's taking extra cycles. It can be a simple average calculated every interval.
9) All the rates used should be logged in the DB. Might make sense to do this with rolling_mean and do it less frequently.
10) The percentile calculation is no longer working as it's meant to. This will be partially fixed by deleting old data, but it should be given a fixed size array and / or resampled in pandas.

**Comment by laxdog** [comment]
11. Outages on getting the rates back cause major hassle. If there's a big enough gap, you're pretty much out of the running (RE: MA) for 30 min (long window)

**Comment by kryztoval** [comment]
6. Something like nedb, but for python? or sqlite? or an actual website that has the historical rates for query? mmmm interesting idea.
7. I like this idea.
8. no need to recalculate the values if you store values in weighted form or precalculated.
9. weighted averages can be precalculated per hourly/daily and still keep 99% accuracy.

**Comment by laxdog** [comment]
6) I'm already storing what I get from Polo in sqlite, which works well when you've been running for a while. What I want is something to get information from the hour before you started the bot. So an actual site that I could query for the info. 

8) I still need to calculate it somehow though, it was more a note to myself to stop using that function. 
9) Yip, though it's more likely to be per second :)
