### ISSUE TITLE
I get this error when accessing to http://myuser.pythonanywhere.com/static/lendingbot.html

### ISSUE THREAD

**Issue by unclemimo** [BitBotFactory/poloniexlendingbot#317]
Hi,

I have set up the bot, and it's running (it has successfully placed an order),

<img width="1436" alt="screen shot 2017-05-05 at 3 12 51 am" src="https://cloud.githubusercontent.com/assets/1642181/25730865/10bd78fe-3141-11e7-88e6-b3cf2c49957d.png">

...but when I try to access to the web server, I got this message:

<img width="1250" alt="screen shot 2017-05-05 at 3 17 23 am" src="https://cloud.githubusercontent.com/assets/1642181/25730914/7961b974-3141-11e7-9401-63a1afbbd0f7.png">

Any ideas?

**Comment by utdrmac** [comment]
"Address already in use" usually means something else is bound to the default port of 8000. `netstat -napt | grep 8000` to see what else is listening on that port. Or set a specific IP and different port in the default.cfg. If you changed it to port 80, then there could be a webserver already listening on that port running on that machine.

**Comment by Evanito** [comment]
Do not use the built in webserver on pythonanywhere, please see the
documentation (under installing on pythonanywhere) on how to set it up with
their website.

**Comment by rnevet** [comment]
@unclemimo is the issue resolved?

**Comment by Evanito** [comment]
Solution given, closing.
