### ISSUE TITLE
Telegram notifications repeat every time it cycles.

### ISSUE THREAD

**Issue by kryztoval** [BitBotFactory/poloniexlendingbot#318]
![image](https://cloud.githubusercontent.com/assets/5733028/25768386/bab925d8-31c8-11e7-9dd7-184178f98a5b.png)

It seems every time this cycles it resends the last notification... for some reason.

**Comment by laxdog** [comment]
Weird, I've not seen the same issue. But I'm using slack for all my notifications. 

Are you sure it wasn't just multiple loans being filled? What's your spreadlend set to @kryztoval ?

Or are you seeing this regularly?

I'll have a quick look at the source anyway.

**Comment by kryztoval** [comment]
I am sure this is not a spread issue, spread is 3. I am sure it was not multiple loans being filled at the same rate, this almost never happens. I am sure this is a bug, as it keeps doing it on every cycle, I am gonna run a blame and see if I find a change between the last version I knew worked and this one

**Comment by laxdog** [comment]
Did you get anywhere with this @kryztoval ? I'm baffled to be honest. 

You could stick a couple of print statements in to see how often it's actually being called what's being sent.

**Comment by kryztoval** [comment]
Sorry for the delay. I couldn't test it. I started getting this instead:
![image](https://cloud.githubusercontent.com/assets/5733028/26039883/5f616ae6-38e5-11e7-8a63-2070f603c90c.png)
Which is ironic because I get the notification in Telegram! and then it dies... I think this has to do with another bug that says that telegram errors are not captured properly.

I reverted to the head version and added just 2 lines I added on my own, (that do nothing for this code) and it shows this behaviour. :/

**Comment by laxdog** [comment]
Very strange. It's still working as expected for me. OK:-
*) What's your platform (Windows / linux / pytonanywhere)
*) Are you behind any proxies / firewalls / loadbalancers
*) Have you checked there's only one bot running
*) What's your python version
*) Which other error, have you a log for it
*) Your Notifications config (Change the IDs for telegram)

**Comment by kryztoval** [comment]
It keeps dying, I'll create a new bot so I can get a new ID.

**Comment by kryztoval** [comment]
Very strange. It's still working as expected for me. OK:-
*) What's your platform (Windows / linux / pytonanywhere)
Linux, Centos 7.3,  Python 2.7.5.
*) Are you behind any proxies / firewalls / loadbalancers
No proxies, no firewalls, no load balancers
*) Have you checked there's only one bot running
Affirmative, only one bot running.
*) What's your python version
See above
*) Which other error, have you a log for it
Only this one after the repeated lines. No other errors after this one showed up
*) Your Notifications config (Change the IDs for telegram)
[notifications]
notify_new_loans = True
notify_tx_coins = False
notify_xday_threshold = False
notify_summary_minutes = 0
notify_caught_exception = False

email = False
slack = False

telegram = True
telegram_bot_id = #########:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
telegram_chat_ids = ########,@aaaaaaaaa

**Comment by laxdog** [comment]
OK @kryztoval , I did a bit of debugging there. I thing either your channel the @aaaaaa or your chat_id ####### are wrong. 

Can you try them one at a time so you can see which is wrong?

If it's the chat_id, you can follow the instructions from http://poloniexlendingbot.readthedocs.io/en/latest/configuration.html#telegram-notifications point number 5 onward. 

If it's the @channel name, then you just need to check you have invited the bot and don't have a typo.

**Comment by kryztoval** [comment]
Are you sure?  I mean, the funny part is that the text I copied for the 400 error is from the telegram chat I have with the bot... it showed up in telegram and also on the program. so how can it be wrong and still show me the message?

![image](https://cloud.githubusercontent.com/assets/5733028/26379483/141e459e-3fdf-11e7-9b85-63cef4a9bb7a.png)

I also just ran the test line below and it works fine. you can see the text at the bottom of the image. So... how can it be wrong?
https://api.telegram.org/bot#########:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/sendmessage?text=This%20is%20a%20test&chat_id=########,@aaaaaaaaa

**Comment by rnevet** [comment]
If it's working it could be that the 400 error was temporary issue,

**Comment by laxdog** [comment]
@kryztoval not 100%, but yea, pretty sure. 

It's showing you that error message in the chat because you have ```notify_caught_exception = True```

If that's the group chat then your personal chat ID is wrong, so it's trying to send a message to your personal chat ID, failing (raising an exception), then telling you on the one that works, the group chat pictured, that it couldn't send a message to it.

You know you don't need both right? You can have it send the message directly to you (the chat_id=######### in your example) or you can have it sent to the group chat (the @aaaaaaa in your example).

The comma separated list for `telegram_chat_ids` is a list of people and channels you want to send the message to. I'd been assuming you wanted to send it to both yourself and a channel.

**Comment by kryztoval** [comment]
Umm, that is the chat_id, I do not have a group chat. So I do not need the bot id? why does the link work then? 
https://api.telegram.org/bot#########:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/sendmessage?text=This%20is%20a%20test&chat_id=########,@aaaaaaaaa
will this call work without the chat id? or without the bot id? I am not sure I am understanding how this is gonna work without both parameters. :/

**Comment by laxdog** [comment]
@kryztoval 

OK, well the chat_id is the one that's working then and the other isn't. The comma that separates the two values in the chat_id (########,@aaaaaaaaa) means that you are sending to two different places. Or trying to at least.

You need the bot id, but that's a separate config. 

You don't need both values each side of the comma in chat_id.

Message me on slack or gitter if you're still online.

**Comment by kryztoval** [comment]
Ok, removed the @aaaaaaaa as you suggested, but the bot is not having notifications to send me yet. I am gonna wait and see if it does something. I guess I am more used to the [this|@that] notation than the this,@that ... :-(

I still don't know why it kept repeating the same message over and over, but it is not doing so anymore.

**Comment by laxdog** [comment]
You can generate a message by setting

```notify_summary_minutes = 1```

**Comment by laxdog** [comment]
Is this working now @kryztoval ? I'd like to close the ticket.

**Comment by kryztoval** [comment]
You may close this, it seems it failed to send to the @aaaaaa and it marked it as an error and retried next minute and send it to both, the correct and incorrect locations. Causing spam.

Removing the incorrect group name fixed this.  😄
