### ISSUE TITLE
500 Internal Server error

### ISSUE THREAD

**Issue by Moulijin** [BitBotFactory/poloniexlendingbot#323]
![capture](https://cloud.githubusercontent.com/assets/2942447/25790777/5432c78e-3370-11e7-9b8e-d1bc2adca966.PNG)
![capture2](https://cloud.githubusercontent.com/assets/2942447/25790780/57132110-3370-11e7-8707-cb5aabd6e800.PNG)

**Comment by laxdog** [comment]
Your MarketAnalysis files are likely corrupt. That's what the null byte thing is.

You can try renaming them if you want to keep the data, or just delete them if you don't care. Then run the bot again. 

The 500 can be ignored, it's an issue on Poloniex (and possible why the files are corrupt too)

I would recommend not running the bot as root by the way, unless you're sure you know what you're doing.
