### ISSUE TITLE
INFO : Slack and telegram

### ISSUE THREAD

**Issue by laxdog** [BitBotFactory/poloniexlendingbot#329]
Just a heads up for those not following the gitter conversation. There is a now a slack channel and telegram group

https://poloniexbot.slack.com/shared_invite/MTc5OTU4MDAzNTY4LTE0OTQzMTA2MzYtZDdkYTg1NjBkYg

https://t.me/mikalendingbot

Edit: Fixed the link

**Comment by rnevet** [comment]
https://poloniexbot.slack.com/shared_invite/MTc5OTU4MDAzNTY4LTE0OTQzMTA2MzYtZDdkYTg1NjBkYg

Non-expiring link.
