### ISSUE TITLE
Not correctly reporting nonce errors

### ISSUE THREAD

**Issue by laxdog** [BitBotFactory/poloniexlendingbot#338]
I noticed this today when doing a doc update for pythonanywhere. I used an old API key and was getting 

```HTTP Error 422:  Requesting returnOpenLoanOffers```

After messing about with pdb I found it was actually

```
(Pdb) ex.read()
'{"error":"Nonce must be greater than 149457735191782915. You provided 1494578980835."}'
```

So these aren't showing the full issue:
```
(Pdb) ex
HTTPError()
(Pdb) str(ex)
'HTTP Error 422: '
(Pdb) ex.message
'HTTP Error 422:  Requesting returnOpenLoanOffers'
```

I'll have a closer look, but I think we might need to do a bit more handling on exceptions when we catch them. 

It's pretty easy to replicate, just set your `req['nonce'] = int(time.time() * 1000)` to `req['nonce'] = int(time.time() * 10)` or something.

**Comment by tisdall** [comment]
Since the API provides an error message, can we just output that?

**Comment by laxdog** [comment]
Yip, we sure can. It's just because of how we're catching them atm.

**Comment by tisdall** [comment]
How about this:
```
diff --git a/modules/Poloniex.py b/modules/Poloniex.py
index 297ef42..4ef3148 100644
--- a/modules/Poloniex.py
+++ b/modules/Poloniex.py
@@ -121,6 +121,15 @@ class Poloniex:
                 ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
                 json_ret = _read_response(ret)
                 return post_process(json_ret)
+        except urllib2.HTTPError as ex:
+            try:
+                data = json.loads(ex.read())
+                polo_error_msg = data['error']
+            except:
+                polo_error_msg = None
+            ex.message = ex.message if ex.message else str(ex)
+            ex.message = "{0} Requesting {1}.  Poloniex reports: '{2}'".format(ex.message, command, polo_error_msg)
+            raise
         except Exception as ex:
             ex.message = ex.message if ex.message else str(ex)
             ex.message = "{0} Requesting {1}".format(ex.message, command)
```

Then in the case you gave I get the following on the console: `2017-06-01 16:48:29 Error: HTTP Error 422:  Requesting returnOpenLoanOffers.  Poloniex reports: 'Nonce must be greater than 1496335535862. You provided 14963357050.'`

**Comment by rnevet** [comment]
@tisdall  I was sure this was handled here:
https://github.com/BitBotFactory/poloniexlendingbot/blob/master/modules/Poloniex.py#L87

It seems something was changed on Polo side, could you make a PR with your suggestion?

**Comment by tisdall** [comment]
@rnevet - It's only handled there if the response is HTTP 200.  The issue is if the response has an error code it's returned as a `urllib2.HTTPError`.  However, according to the docs, that exception can be handled in the same way as the return value from `urlopen` so you can read the body contents (if any).  I put it in a try-except block because it's possible to get an HTTP error code with no usable body.

As laxdog said, you can just change the nonce calculation to force it to return an error and you get back the message I quoted above.

The API docs are pretty lacking because it doesn't state anywhere when you get HTTP error codes and when you don't.

**Comment by tisdall** [comment]
...  making a PR now.
