### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by Zeek1010** [BitBotFactory/poloniexlendingbot#341]
Im getting an error: Could not send email, got error Connection unexpectedly close:timed out. Error during summary notification: Connection unexpectedly close:timed out

My settings are:
[notifications]
notify_new_loans = False
notify_tx_coins = False
notify_xday_threshold = True
notify_summary_minutes = 1
notify_caught_exception = False

email = True
email_login_address = zachary.xxx@rocketmail.com
email_login_password = xxxxxxxxx
email_smtp_server = smtp.mail.yahoo.com
email_smtp_port = 465
email_smtp_starttls = False
email_to_addresses = zachary.xxx@rocketmail.com

Thank you for the help

**Comment by Evanito** [comment]
Off of: https://help.yahoo.com/kb/SLN4724.html
```
Outgoing Mail (SMTP) Server

Server - smtp.mail.yahoo.com
Port - 465 or 587
Requires SSL - Yes
Requires TLS - Yes (if available)
```
So try port 587, and/or starttls = True

**Comment by Zeek1010** [comment]
That worked! Thank you so much!
