### ISSUE TITLE
Editing the cfg file remotely

### ISSUE THREAD

**Issue by Reno007** [BitBotFactory/poloniexlendingbot#342]
Have the bot running on my Raspberry Pi. Is there any way to quickly remotely edit the cfg file (in case rates spike) on the PI (ideally from my android phone) and then reset the bot? I found some general RP mangement apps but those only let me copy files, not edit them. Have tried VNC but using the remote desktop of the PI is not ideal on a phone. Anyone have a more practical way of managing this?

**Comment by laxdog** [comment]
This is a pretty general question, that isn't really anything to do with the bot...

Anyway. If I was going to do that, I'd use SSH (termux is good, there are others) on your phone to connect to the Pi. Then edit the file directly on the Pi with something like nano (a text editor).

You can then restart the bot from the ssh session too.

**Comment by laxdog** [comment]
General discussion question and seems to be done. Closing.
