### ISSUE TITLE
"Lended" is not a word

### ISSUE THREAD

**Issue by Orteko** [BitBotFactory/poloniexlendingbot#344]
The codebase refers to 'lended' throughout and this is output as part of the log - this is not actually a word and should be replaced with 'loaned'.

Should just be a simple search/replace across all files to fix, happy to submit a pull request with this change in place.

**Comment by rnevet** [comment]
Legacy issue, happy to see a PR. However, "lent" is shorter and afaik correct as well.

**Comment by Orteko** [comment]
No worries, i'll knock up a PR and send it through later on.

Given that the poloniex page is titled 'lending' rather than 'loans' it would be more consistent to use 'lent' so i'll base it on that.
