### ISSUE TITLE
Minloansize has changed

### ISSUE THREAD

**Issue by lexrms** [BitBotFactory/poloniexlendingbot#347]
Hi guys,

Poloniex changed the policy for several currencies.

Here are some that I checked.

BTS = 10
CLAM = 10
DOGE = 100
FCT = 100
MAID = 10
STR = 100
XRP = 100

Thank you

**Comment by Evanito** [comment]
Wow, 10 CLAM min is going to hurt me, thanks for the heads up.

After the last time this happened, I implemented automatic increasing of the min based on the reply from poloniex. So have no fear, the bot will adjust to this automatically.

**Comment by lexrms** [comment]
Note this: XRP = 100, Btc = 0.00019124; BTS = 10, Btc = 0.00002836
Do we have any logic in this?
Is this going to make certain currencies get more expensive with less loan supply? Or even make more people buy to have the minimum quantity of each coin?

**Comment by Evanito** [comment]
It is a strange move, likely based on which coins happen to be spammed by many small orders.

**Comment by Evanito** [comment]
Closing because discussion on this is not necessary here
