### ISSUE TITLE
Error in MarketAnalysis

### ISSUE THREAD

**Issue by rmy-s** [BitBotFactory/poloniexlendingbot#350]
Getting this error repeatedly, unsure how to fix?

> Error in MarketAnalysis: list index out of range
> WARN: Exception found when analysing markets, if this happens for more than a couple minutes please make a Github issue so we can fix it. Otherwise, you can s
> afely ignore it. Error: list index out of range

**Comment by rmy-s** [comment]
#

**Comment by Evanito** [comment]
The list index out of range error is usually due to your market data being malformed, recently this is probably due to Poloniex lagging. Please delete the data files in the market_data/ folder and they should be remade.

**Comment by Evanito** [comment]
**Closing issue because a solution has been found.**

If your error persists or you have another error *that is related to this one* please reopen this issue so we can find another solution. If you have any other problems please open a new issue.

Thank you for using Poloniexlendingbot.
