### ISSUE TITLE
coinconfig or coincfg

### ISSUE THREAD

**Issue by tisdall** [BitBotFactory/poloniexlendingbot#352]
The default.cfg.example has a `coinconfig` option but the docs talk about `coincfg`.  The docs also describe the component values slightly differently than the the config file.

**Comment by rnevet** [comment]
I recommend using the coin specific section, coinconfig will be removed at some point. (When I get to it)

Config is complicated and needs work.

**Comment by rnevet** [comment]
Discussion regarding removing coinconfig option.
https://github.com/BitBotFactory/poloniexlendingbot/issues/364
