### ISSUE TITLE
Server doesn't work

### ISSUE THREAD

**Issue by v0ku** [BitBotFactory/poloniexlendingbot#356]
Hi,

the bot opens lends, but the localhost server window doesn't contain any information except: 

```
Poloniex Lending Bot
Not updated

 Settings 
Status
N/A
Log (Reversed ordered):

```
The command shell contains the subsequent text: 
```
Welcome to Poloniex Lending Bot 
Started Webserver, lendingbot status available at: _several IP adresses_
```

That's it. Any idea what might be the reason?

**Comment by rnevet** [comment]
Please attach relevant settings from config.

**Comment by v0ku** [comment]
```
jsonfile = www/botlog.json
jsonlogsize = 200
startWebServer = true
```

Or do you mean something else? My settings are pretty basic and I've followed the initial instructions.

**Comment by rnevet** [comment]
See if bootlog.json exists in www an if it is accessible from the browser.

**Comment by v0ku** [comment]
It does and I'm able to open it. It contains information about a configured coin in a single row.

**Comment by rnevet** [comment]
what url are you using to open the html?

**Comment by v0ku** [comment]
At the moment I open it via http://127.0.0.1:8000/lendingbot.html

**Comment by rnevet** [comment]
and http://127.0.0.1:8000/bootlog.json works? (This is the URL that HTML uses.)

**Comment by v0ku** [comment]
No, HTTP 404 - Not found

**Comment by rnevet** [comment]
Can you try refreshing (CTRL + F5) the http://127.0.0.1:8000/lendingbot.html page?

**Comment by v0ku** [comment]
Refreshing works, but the page keeps not updated. Is it correct that I always have to reconfigure the settings after shutting down the server with Ctrl+C?

**Comment by rnevet** [comment]
It is correct that config changes are only applied after bot is restarted
So you are able to access lendingbot.html bot not bootlog.json and both are under the www folder?
What env are you using?

**Comment by mike4001** [comment]
Just wanted to point out that it is botlog.json and not bootlog.json

So http://127.0.0.1:8000/botlog.json should work :-)

**Comment by rnevet** [comment]
@mike4001 Thanks! Lets see.

**Comment by noonway** [comment]
Just wanted to say I was having the same problem after pulling latest from git and a Ctrl+F5 refresh worked for me.

**Comment by v0ku** [comment]
@mike4001 It shows an unformatted row in the browser, yes. 
@rnevet Yes, both are in the same folder. Ctrl+F5 doesn't change anything. Window content stays the same :/

Win 10 , 64bit , Internet Explorer 11.2, Python 2.7.13

**Comment by mike4001** [comment]
I am no expert but maybe try a browser thats not Internet Explorer.

Since apparently the botlog.js shows content and you can also see the lendingbot.html maybe this is the culprit.

**Comment by v0ku** [comment]
With Chrome it works -.-

**Comment by rnevet** [comment]
Damn Microsoft!!!

**Comment by Evanito** [comment]
Closing due to solution found
