### ISSUE TITLE
Numpy and hypothesis = blocked bot ?

### ISSUE THREAD

**Issue by tofm2** [BitBotFactory/poloniexlendingbot#359]
Hello, I have recently noticed that my bot seems to be stuck at 24th of may, nothing happens, all loans are stopped, and log does not roll any longer.

On an other hand, I saw the requirements.txt recently appeared. It seems that some numpy and hypothesys python libs are now required. 

How can I install those libs on my pythonanywhere host to see if this restores bot's will to work ??

Thanks for your help.

**Comment by rnevet** [comment]
AFAIK, hypothesys isn't required for regular runs, did you try restarting your bot? try removing hypothesys from the requirements.txt.

**Comment by laxdog** [comment]
Hypothesis isn't on there, this is pythonanywhere output:
```
16:33 ~ $ python2
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import hypothesis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named hypothesis
>>> 
```

That said, it shouldn't be using it, so I don't think that's your problem.

**Comment by laxdog** [comment]
Old issue with no updates. Open another @tofm2 if you need.
