### ISSUE TITLE
Improve load times by self hosting static CSS/JS

### ISSUE THREAD

**Issue by kingo55** [BitBotFactory/poloniexlendingbot#360]
Self hosting external files will definitely help improve load times - particularly for international users.

Also makes for one fewer (no matter how unlikely) security concern from hosting JS externally.

**Comment by rnevet** [comment]
Well, I'm not sure if serving the files from my DO or from PYA will be faster then CDNs

**Comment by tamaskan** [comment]
can you demonstrate the improved load times ?

**Comment by Evanito** [comment]
These things (JS Libraries) are usually cached by the browser the first time you access them. For our purpose, I think it would be best to keep the dependence.

**Comment by laxdog** [comment]
I agree with @Evanito here, there's no reason to do this as the JS will always be cached.
