### ISSUE TITLE
Year Earnings

### ISSUE THREAD

**Issue by lexrms** [BitBotFactory/poloniexlendingbot#368]
Can someone take a look at these earnings and check please?

I updated the bot today.

I believe the problem is in the calculation of CLAM.

![2017-06-05 17-30-49](https://cloud.githubusercontent.com/assets/13912856/26802128/b7927250-4a15-11e7-8610-3ff842acc828.png)

**Comment by rnevet** [comment]
That does look weird.

**Comment by lexrms** [comment]
Yes. This has happened since the yearly gain was implemented.

I can send the file.

How do I find you on the telegram?

**Comment by Evanito** [comment]
If you believe it is related to CLAM, can you share a screenshot of your rates just in the CLAM market? (Like the image above, but CLAM instead of summary.)
