### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'SMTPServerDisconnected' objects

### ISSUE THREAD

**Issue by blacktemplar** [BitBotFactory/poloniexlendingbot#374]
I just wanted to try the email notification and got the following errors:

Could not send email, got error Connection unexpectedly closed
python2.7[30270]: Error during summary notification: Connection unexpectedly closed
python2.7[30270]: Could not send email, got error Connection unexpectedly closed
python2.7[30270]: Traceback (most recent call last):
python2.7[30270]:   File "/home/bene/tools/poloniexlendingbot/lendingbot.py", line 90, in <module>
python2.7[30270]:     log.log_error(ex.message)
python2.7[30270]:   File ".../poloniexlendingbot/modules/Logger.py", line 97, in log_error
python2.7[30270]:     log_message = self.timestamp() + ' Error: ' + msg
python2.7[30270]: TypeError: cannot concatenate 'str' and 'SMTPServerDisconnected' objects

THe first two Errors seem to be normal as something went wrong with the email notification, but the last one seems to be a python exception!

**Comment by laxdog** [comment]
I think it's a bug in how the exception message is being handled for printing / notifications. 

I'll take a look at it.
