### ISSUE TITLE
Fix maxtolendrate

### ISSUE THREAD

**Issue by melo52** [BitBotFactory/poloniexlendingbot#376]
Currently, maxtolendrate is compared to the lowest rate on the lendbook, rather than the lowest rate offered by the bot.

If I set: xdaythreshold = .2, xdays = 60, maxtolendrate = .2, maxpercenttolend = 50

Any loan offered over .2 should last for 60 days and use 100% of the available balance.

What actually happens is that if there is a dust offer on the lend book, it does offer for 60 days but only uses 50% of the available balance.

**Comment by rnevet** [comment]
what is your maxtolend ?

**Comment by melo52** [comment]
i do have it written as .2 for both xdaythreshold and maxtolendrate.  it seems to recognize it ok.  I will change it to 0.2 and see what happens.

**Comment by melo52** [comment]
I think it worked!  thanks.

**Comment by rnevet** [comment]
Great
