### ISSUE TITLE
Lendingbot not starting

### ISSUE THREAD

**Issue by robsske** [BitBotFactory/poloniexlendingbot#379]
Hello, when i run the main python script i get:

Welcome to Poloniex Lending Bot
Lent:

Cant type anything after: Lent:
Why is this? Because there are no coins available or something?

**Comment by tamaskan** [comment]
1) you need to have coins for the bot to lend them
2) you should start the bot with "sudo systemctl start lendingbot.service" ( if you followed the instruction "Automatically Run on Startup" ) http://poloniexlendingbot.readthedocs.io/en/latest/installation.html#installing-on-a-computer

**Comment by Evanito** [comment]
If no coins are lent, then there will be no message.

**Comment by utdrmac** [comment]
@robsske Are you good? Can this be closed?

**Comment by laxdog** [comment]
No reply in too long. Closing.
