### ISSUE TITLE
[Feature request] With Maxtolend, all coins are still transfered to lending

### ISSUE THREAD

**Issue by Fire69** [BitBotFactory/poloniexlendingbot#383]
Hey,

I have maxtolend = 0.5, this is working correctly, only 0.5BTC are lent.
But, all my coins are transferred to lending balance, which I don't like because when I want to trade I have to move them back to exchange balance.
And I have to be quick, because the bot sends them back to lending again :-)

Would the be something that can be changed? Or made configurable?

Thanks!

**Comment by rnevet** [comment]
Did you see this one? 
https://github.com/BitBotFactory/poloniexlendingbot/issues/371

**Comment by Fire69** [comment]
Obviously not :-P
Sorry, I'll close this one :-)
