### ISSUE TITLE
Error: The read operation timed out Requesting "returnAvailableAccountBalances / returnActiveLoans / returnOpenLoanOffers / createLoanOffer"

### ISSUE THREAD

**Issue by djcrawleravp** [BitBotFactory/poloniexlendingbot#386]
It started about 2 hours ago.

The bot is not lending anything and giving me these messages

![screen shot 2017-06-12 at 10 45 31](https://user-images.githubusercontent.com/12896341/27039585-4fa287a6-4f5c-11e7-963c-5f02b2cbe95b.png)

**Comment by rnevet** [comment]
Poloniex API not responding is causing it. :(  Nothing you can do at the moment.

**Comment by utdrmac** [comment]
This is an issue with poloinex. They are experiencing some load issues.

**Comment by djcrawleravp** [comment]
Bummer...

Thanks guys, I think I reinstalled everything in vain then :/

**Comment by limerick11** [comment]
Does this mean the API is not working and it won't be able to place any loans?

**Comment by rnevet** [comment]
Increasing the timeout might help, there is a PR in the oven.

**Comment by djcrawleravp** [comment]
where in my default.cfg do i increase the timeout?

**Comment by rnevet** [comment]
you can't it isn't a configuration option yet.

Can manually change here:
https://github.com/BitBotFactory/poloniexlendingbot/blob/master/modules/Poloniex.py#L55

**Comment by djcrawleravp** [comment]
Just change the number to (let's say 120) and then reboot right?

**Comment by rnevet** [comment]
yes, that would be a 2min timeout then.

**Comment by djcrawleravp** [comment]
Thank you so much @rnevet
