### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by limerick11** [BitBotFactory/poloniexlendingbot#394]
Hi all,
The readme states that is it possible to 'Run multiple instances of the bot for multiple accounts easily using multiple config files.'. How do I configure this? I couldn't find any documentation on this.

Thanks

**Comment by rnevet** [comment]
http://poloniexlendingbot.readthedocs.io/en/latest/installation.html#running
using -cfg in the command line.

However I think this might not work with Market Analysis or Account Stats.

**Comment by limerick11** [comment]
Thanks @rnevet. So i'll need to create a custom web server address too?
