### ISSUE TITLE
Lower analyseMaxAge limit for Local Market Analysis

### ISSUE THREAD

**Issue by Wegerich** [BitBotFactory/poloniexlendingbot#399]
With the loan rates fluctuating a lot recently I've found myself loving the bot - until about a month ago I was using a 2 year old version and I was delighted to find that it had been expanded with many features I'd have loved and not known how to do myself as a very amateur coder. 

I played with Local Market Analysis (LMA) a little bit but ended up turning it off because I found that the volatile rates meant that it was leaving coins un-loaned for much longer than I would like when rates had spiked for a day. 

However, I do still see rates spike downwards temporarily, then my loans get swooped at a low rate when they come back up.

I've set my analyseMaxAge to "1" and lendingStyle to "10" but I would like to be more aggressive over a shorter time period to catch spikes but adjust quickly if things are really dropping. Would this be possible?

**Comment by rnevet** [comment]
I suggest you check out the macd branch.

**Comment by laxdog** [comment]
Yip, please do check out the macd branch @Wegerich , ping me if you have any trouble getting it working. 

You should notice much better lending rates and percentage lent out.

**Comment by Wegerich** [comment]
How do I access that? Can you post a link please? I'm not well versed with github.  
Thank you @laxdog

**Comment by laxdog** [comment]
Yea, it's on page on my fork. I started it before I was a member of this organisation.
