### ISSUE TITLE
Error text too long ...

### ISSUE THREAD

**Issue by mike4001** [BitBotFactory/poloniexlendingbot#402]
Hi

Today I had the error (see screenshot). I think you should add a maximum amount of characters since Poloniex return a complete website for this one.

![unbenannt](https://user-images.githubusercontent.com/26521177/27317022-0942b5aa-5584-11e7-80f6-e9c4ac903155.jpg)

**Comment by tamaskan** [comment]
i think its better to add a exception like https://github.com/BitBotFactory/poloniexlendingbot/commit/38ac656d5ce37c8624f4686096589680b911a3bf

**Comment by rnevet** [comment]
Yeah, saw that one as well...  would add it to the exceptions like tamaskan suggested.  A PR would be appreciated.

**Comment by tisdall** [comment]
Maybe we should extend #392 to include error code 522?  Apparently that's a Cloudflare specific error code that seems pretty similar to 502:  https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522-Connection-timed-out

It looks like there's error codes 520 through to 526 that Cloudflare may return resulting in a whole web page.  We should just ignore the body with any of those errors...

...  just clicked @tamaskan 's link and see they're saying the same thing.  ;)

**Comment by mchl18** [comment]
```
            except:
                if ex.code == 502 or ex.code == range(520, 526, 1):  # 502 and 520-526 Bad Gateway so response is likely HTML from Cloudflare
                    polo_error_msg = ''
```

**Comment by mchl18** [comment]
makin a PR, cant test it though. when does this happen?

**Comment by utdrmac** [comment]
@Evanito Please re-open. @mchl18 Please re-examine. I received this twice today.

<img width="1236" alt="screen shot 2017-08-14 at 3 39 16 pm" src="https://user-images.githubusercontent.com/4413670/29290819-176cbe9c-8107-11e7-8729-f1c6b911d698.png">

**Comment by mchl18** [comment]
So that is the cloudflare html that is supposed to be blocked?

**Comment by tisdall** [comment]
Yes, Cloudflare...  The code committed should have fixed that, though.

**Comment by mchl18** [comment]
I don't think I'll be able to provoke this, but should be fixed with PR...

**Comment by mchl18** [comment]
if you can provoke it, can you debug into it somehow? @utdrmac

**Comment by utdrmac** [comment]
Ah. My screenshot is from the recent BITFINEX merge. I see your PR only deals with Poloniex. Can you add the cloudflare checks to Bitfinex too?

**Comment by mchl18** [comment]
are you lending with bitfinex?

**Comment by utdrmac** [comment]
Yep. Polo is dead on lending. Currently 0 BTC demand.

**Comment by utdrmac** [comment]
Lending ETH, BCH and BTC on bitfinex with the recent merge.

**Comment by mchl18** [comment]
Okay, i really can't test this bc I am not lending on bitfinex right now... but
```
def _request(self, request, command, payload=None, verify=True):
        try:
            r = {}
            if (request == 'get'):
                r = requests.get(self.url + command, timeout=self.timeout)
            else:
                r = requests.post(self.url + command, headers=payload, verify=verify, timeout=self.timeout)

            if r.status_code != 200:
                if (r.status_code in [502, 504, 522]):
                    raise ApiError('API Error ' + str(r.status_code) +
                                   ': The web server reported a bad gateway or gateway timeout error.')
                else:
                    raise ApiError('API Error ' + str(r.status_code) + ': ' + r.text)

            return r.json()

        except Exception as ex:
            ex.message = ex.message if ex.message else str(ex)
            ex.message = "{0} Requesting {1}".format(ex.message, self.url + command)
            raise ex
```

could also be 

`if (r.status_code == 502 or in r.status_code in range(502, 527, 1)):`

since they seem to behave the same

**Comment by utdrmac** [comment]
I'll test it

```
[root@gasgiant bitfinex]# git diff modules/Bitfinex.py
diff --git a/modules/Bitfinex.py b/modules/Bitfinex.py
index 4a281da..f53c584 100644
--- a/modules/Bitfinex.py
+++ b/modules/Bitfinex.py
@@ -52,7 +52,7 @@ class Bitfinex(ExchangeApi):
                 r = requests.post(self.url + command, headers=payload, verify=verify, timeout=self.timeout)

             if r.status_code != 200:
-                if (r.status_code in [502, 504, 522]):
+                if (r.status_code == 502 or in r.status_code in range(502, 527, 1)):
                     raise ApiError('API Error ' + str(r.status_code) +
                                    ': The web server reported a bad gateway or gateway timeout error.')
                 else:
```

**Comment by mchl18** [comment]
cool, submitting the PR

**Comment by rnevet** [comment]
@mchl18 You need to install requests. It's explained in other issues.

**Comment by mchl18** [comment]
maybe you reopen this issue for the sake of bitfinex testing.
I have just pushed to my fork, the code should fix the issue, although I must say I am not really able to test, since I wanted to suspend lending on polo and do not have anything on bitfinex right now.
My commit history has some commits in there that were pointless,  I was getting used to Github workflow, sorry.

**Comment by mchl18** [comment]
codebeat declined the code, but I either I do not understand it or it is not due to my changes.

**Comment by tisdall** [comment]
@mchl18 - I'm glad you noticed that it was missing the 526 error code (not sure how much that happens, but also a Cloudflare error code).

**Comment by rnevet** [comment]
"maybe a shared error message would be reasonable." I agree.

Did you make a PR? I don't see one.

**Comment by mchl18** [comment]
Well, here is the PR with the basic changes. The last commit is relevant, as I said, I had some issues with workflow.

**Comment by rnevet** [comment]
That's not an issue, we'll squash the commits and merge.
