### ISSUE TITLE
Error :  urlopen error....

### ISSUE THREAD

**Issue by parames3010** [BitBotFactory/poloniexlendingbot#403]
![screenshot_43](https://user-images.githubusercontent.com/8073243/27318315-df39fa3e-55b5-11e7-91e6-916be6fccf47.png)

how to fix this?
i run on aws vps it error
but when i try on my pc it not error  why?

**Comment by utdrmac** [comment]
Probably because your PC has all the root certificates installed and your EC2 does not. Look for a Windows package for all the root certificates or you may need to install them in a way that python can find them.

**Comment by laxdog** [comment]
Can this be closed @parames3010 ?

**Comment by parames3010** [comment]
yes


________________________________
จาก: Michael Robinson <notifications@github.com>
ส่ง: 4 สิงหาคม 2560 15:06
ถึง: BitBotFactory/poloniexlendingbot
สำเนาถึง: parames3010; Mention
ชื่อเรื่อง: Re: [BitBotFactory/poloniexlendingbot] Error : urlopen error.... (#403)


Can this be closed @parames3010<https://github.com/parames3010> ?
