### ISSUE TITLE
Unknown format code 'f' for object of type 'str'

### ISSUE THREAD

**Issue by HostFat** [BitBotFactory/poloniexlendingbot#407]
The bot seems that it isn't working anymore.

```
raceback (most recent call last):
  File "lendingbot.py", line 79, in <module>
    Lending.lend_all()
  File "/home/poloniexlendingbot/modules/Lending.py", line 227, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/home/poloniexlendingbot/modules/Lending.py", line 423, in lend_cur
    raise msg
ValueError: Unknown format code 'f' for object of type 'str'
```

**Comment by rnevet** [comment]
What gapmode are you using?

**Comment by HostFat** [comment]
Relative

Anyway, it seems that setting hideCoins back to "True" and restarting the bot has fixed it, maybe this can be useful to find the bug :)

**Comment by rnevet** [comment]
Can you try to reproduce it again? i.e. set hideCoin to False? just to make sure it is related and not a server response issue?

**Comment by HostFat** [comment]
Yes, I confirm that just after changing it to "False" and restarting the bot it gives back the error.

**Comment by laxdog** [comment]
Do you know what version from git you are running @HostFat ? I can't reproduce this.

**Comment by utdrmac** [comment]
@HostFat Is this still an issue with latest git HEAD? If not, please close.
