### ISSUE TITLE
Too many time outs

### ISSUE THREAD

**Issue by otaviobps** [BitBotFactory/poloniexlendingbot#408]
Hi everyone, I'm getting too many time out errors, i.e:

Error: <urlopen error timed out> Requesting returnActiveLoans
Error: <urlopen error timed out> Requesting createLoanOffer
Error: <urlopen error timed out> Requesting returnActiveLoans
And many mores.

I guess it's the Poloniex website with a huge latency, but is there an optimal configuration to bypass this? I set the sleeptimeactive to 5 and sleeptimeinactivo to 5.

My timeout configuration is set to 120, but it's commented, should I remove the #?

**Comment by rnevet** [comment]
yes remove the #, you can try 90 sec as well. 

Otherwise nothing else you can do but complain.

**Comment by otaviobps** [comment]
Removed the # and set the timeout to 120. Everything working fine now. Thanks
