### ISSUE TITLE
Error in MarketAnalysis: line contains NULL byte

### ISSUE THREAD

**Issue by mlai88** [BitBotFactory/poloniexlendingbot#413]
Error in MarketAnalysis: line contains NULL byte
WARN: Exception found when analysin markets, if this happens for more than a couple minutes please make a Github issue so we can fix it. Otherwise, you can safely ignore it.

**Comment by tamaskan** [comment]
Is it possible to automate the deletion of faulty MarketAnalysis-Data ?

**Comment by rnevet** [comment]
MarketAnalysis data as CSV is soon to be deprecated, MACD branch is using sqlite.

**Comment by tamaskan** [comment]
great news :-)
