### ISSUE TITLE
[docs] What is the unit for maxactiveamount?

### ISSUE THREAD

**Issue by pricejn2** [BitBotFactory/poloniexlendingbot#415]
As this is a required parameter for any configuration in the separate coin sections, I think we should clarify what this value represents.
- Is there a value that represents all available?
- Is this coin relative? For example, 1 BTC is much different than 1 DOGE.

Thanks!

**Comment by rnevet** [comment]
It's either 0 or 1 (disabled, enabled), it's a legacy mistake - didn't rename it as it would break all configs.

**Comment by pricejn2** [comment]
Thanks!
