### ISSUE TITLE
lendingbot.html Timing out

### ISSUE THREAD

**Issue by silverstar194** [BitBotFactory/poloniexlendingbot#421]
My lendingbot.html  landing page is timing out. It was running fine and I can back the next day and broken.

**Comment by tamaskan** [comment]
that is the fault of your server, the bot is not responsible for that

**Comment by rnevet** [comment]
1. It's very unlikely that the lendingbot.html is timing out. (if it is then it's your own setup issue)
2.  If you are seeing the timeout in the logs please increase the timeout value in your config. There have been many discussions and issues regarding this subject a short search will help you.
