### ISSUE TITLE
MarketAnalysis gets stuck on the a rate

### ISSUE THREAD

**Issue by CrossyFTW** [BitBotFactory/poloniexlendingbot#422]
My bot very often will get "stuck" on a rate (see copy below), not changing the threshhold rate that the market analysis function is calculating (this can go on for many hours, with the same rate coming through). It is above the manually set minrate for BTC, so it's not that. 

The only way I have found to resolve it is to delete my marketdata file and restart the bot, but then it gets stuck again after working for a while - plus I lose historic data.

Any help - much appreciated!

> 2017-07-11 06:26:41 Not lending BTC due to rate below 0.0749% (actual: 0.0552%)
> 
> 2017-07-11 06:28:52 Not lending BTC due to rate below 0.0749% (actual: 0.0557%)
> 
> 
> 2017-07-11 06:30:57 Not lending BTC due to rate below 0.0749% (actual: 0.0557%)
> 
> 2017-07-11 06:33:07 Not lending BTC due to rate below 0.0749% (actual: 0.0556%)
> 
> 2017-07-11 06:35:10 Not lending BTC due to rate below 0.0749% (actual: 0.0525%)
> 
> 2017-07-11 06:37:17 Not lending BTC due to rate below 0.0749% (actual: 0.0546%)
> 
> 2017-07-11 06:39:27 Not lending BTC due to rate below 0.0749% (actual: 0.0522%)
> 
> 2017-07-11 06:41:32 Not lending BTC due to rate below 0.0749% (actual: 0.0521%)

**Comment by rnevet** [comment]
If you are averaging on many days this might happen, reduce the days in order to have more dynamic value (2 - 3 days).

**Comment by CrossyFTW** [comment]
I have it set to 1 day - analysis still gets stuck on the exact same rate for many hours.

**Comment by rnevet** [comment]
There might be a bug here, however I prefer not to dive into it as the current MarketAnalysis implementation is being replaced by the MACD branch.
https://github.com/BitBotFactory/poloniexlendingbot/pull/292

**Comment by CrossyFTW** [comment]
Oh awesome, I'll wait for that to be merged then! Thanks again
