### ISSUE TITLE
AccountStats plugin values don't match Polo values

### ISSUE THREAD

**Issue by utdrmac** [BitBotFactory/poloniexlendingbot#426]
Tagging @rnevet since he's the author of said plugin.

Looking at this page, https://poloniex.com/tradeHistory#analysis/BTC/-/lending, says "Total with Fees: X.XXXXX BTC" But looking at the plugin output, I see this:

`2017-07-23 21:03:32 Earnings: | ---------- | 0.0000678 BTC Yesterday | Y.YYYYYY BTC in total |

Shouldn't X.XXXX == Y.YYYY?

Additionally, when using this url, https://poloniex.com/tradeHistory#analysis/BTC/-/lending/1500854400/1500940799 to look at "from yesterday", the 'total with fees' number is also different from what the bot says. Looks like "yesterday" for Polo means "today -1 day, from midnight to 11:59:59PM"

**Comment by utdrmac** [comment]
If the bot is "more correct" or "more accurate", please describe/explain why that is over Polo's calculations. Thanks!

**Comment by rnevet** [comment]
@utdrmac 
First I think there is a bug in the Yesterday calculation, I haven't found the time to find it. It seems to return the right value after the first run but the following days seem to me like lower then expected. 

Secondly there will be a difference as Poloniex calculates with fees and the bot tries to calculate netto earned. i.e. the bot value should be Polo Value - 15% fee.

**Comment by utdrmac** [comment]
Ack on 'yesterday' bug. The difference is a lot more than 15%.

**Comment by utdrmac** [comment]
I looked at this today. Such odd logic that Polo API returns most-recent trade activity first but returns all other history latest activity first. The calculations appear correct, as you said, on first run. Will wait until tomorrow/more activity to see if I was wrong all along.

**Comment by utdrmac** [comment]
@rnevet 
https://pastebin.com/eCDqzWaE

I'm finding that the API is not returning all data when given a range. Even for "today", I'm getting back an empty JSON array but when I look at the report, I can see 10+.

The only time I'm getting back all data for a specific date is when I query for all trade history. If I use start time of 0 or start time >= my first lend, I get everything.

But if I set a 'start' that is just 1 day after my first lend, I do not get all data.

**Comment by utdrmac** [comment]
Closing in favor of #521
