### ISSUE TITLE
ERROR: [...]-minloansize's value: '0.001' is below the minimum limit: 0.01

### ISSUE THREAD

**Issue by mchl18** [BitBotFactory/poloniexlendingbot#429]
Hey, I have created a scenario in which the bot crashes.
I am on master and just pulled.
When the minloansize is set below market minimum, it will stop working. 
I will look into the code, the error should be catchable.

<img width="1271" alt="screen shot 2017-07-25 at 17 15 57" src="https://user-images.githubusercontent.com/6136970/28579667-8b8371fe-715d-11e7-974c-8625f4415a92.png">

**Comment by mchl18** [comment]
Shouldn't it be more like this?
<img width="902" alt="screen shot 2017-07-25 at 17 33 45" src="https://user-images.githubusercontent.com/6136970/28580366-8dc18d14-715f-11e7-9381-db3af41002e1.png">
Instead of 
<img width="893" alt="screen shot 2017-07-25 at 17 35 03" src="https://user-images.githubusercontent.com/6136970/28580411-b610a868-715f-11e7-9ab9-c9dbe2d73c11.png">

Seems to be working

**Comment by rnevet** [comment]
What crash are you getting?

**Comment by mchl18** [comment]
So when I turn on this 
<img width="505" alt="screen shot 2017-07-25 at 17 52 43" src="https://user-images.githubusercontent.com/6136970/28581281-225fc57e-7162-11e7-9434-377898223a4a.png">

int he config, it simply stops working. 
I am new to python, maybe I am getting something wrong, but I can't even CTRL-C out of it after that.

The error I am getting is in the first screenshot, bottom

**Comment by mchl18** [comment]
relevant config:


[BOT]
#Sleeps between active iterations, time in seconds (1-3600)
sleeptimeactive = 100

#Sleeps between inactive iterations, time in seconds (1-3600)
#Set to the same value as sleeptimeactive to disable
sleeptimeinactive = 100

#Timeout in seconds, the bot shall wait for a response during each request
#timeout = 30

#Minimum daily lend rate in percent (0.0031-5)
#Setting to 0.0031 is about 1% a year, not worth it.
mindailyrate = 0.02

#Maximum lending rate. 2% is good choice because it's default at margin trader interface.
#5% is the maximum rate accepted by the exchange (0.003-5)
maxdailyrate = 5

#The number of offers to split the available balance across the [gaptop, gapbottom] range. (1-20)
spreadlend = 5

#The depth of lendbook to move through before placing the first (gapbottom) and last (gaptop) offer.
#If gapbottom is set to 0, the first offer will be at the lowest possible rate.
#However some low value is recommended to skip dust offers.
# Gap modes: Raw, RawBTC, Relative
gapMode = RawBTC
gapbottom = 20
gaptop = 200

#Daily lend rate threshold after which we offer lends for x days as opposed to 2.
#If set to 0 all offers will be placed for a 2 day period (0.003-5)
xdaythreshold = 0.2
xdays = 60

#Auto-transfer of funds from exchange to lending balance.
#Enter ALL to transfer all coins, enter ACTIVE to transfer any coins you have in your lending account when the bot starts, these can be mixed.
#The currencies you enter below (comment it out to disable entirely, just leaving empty will result in an error) will be automatically transferred from your exchange balance to your lending balance whenever you deposit them.
transferableCurrencies = STR,BTC,BTS,CLAM,DOGE,DASH,LTC,MAID,XMR,ETH,FCT
#XRP

#Minimum loan size, the minimum size of offers to make, bigger values prevent the bot from loaning small available amounts but reduce loan fragmentation.
minloansize = 0.01

#Keep Stuck Orders - Sometimes an order gets partially filled. When this happens it may leave the remainder of your coin under the set minloansize.
#If this happens, KeepStuckOrders will keep your order where it is so maybe it can be filled. Otherwise it will be canceled and held until orders expire.
keepstuckorders = True

#Hide coins - Instead of keeping your coins lent out at minlendrate when it is not met, the bot will hold them and wait for the rate to surpass it.
hideCoins = True

#End date for lending, bot will try to make sure all your loans are done by this date so you can withdraw or do whatever you need.
#Uncomment to enable.
#Format: YEAR,MONTH,DAY
#endDate = 2016,12,25

#Raw maximum amount to lend if under maxtolendrate.
#If set to 0 or commented: the bot will check for maxpercenttolend.(0+)
#maxtolend = 0

#Maximum percent to lend if under maxtolendrate.
#If set to 0 or commented: the bot will lend 100% of your balance regardless of rate. (0-100)
#maxpercenttolend = 0

#Max to lend conditional rate.
#If set to more than 0: the maxtolend or maxpercenttolend will be used when the rate is less than or equal to the maxtolendrate.
#If set to 0 or commented: the bot will use the maxtolend or maxpercenttolend all the time. (0.0031-5)
#maxtolendrate = 0

# Local Market Analysis: Choose which coins to record the market of in order to analyse them and compute a recommended lending rate.
# Enter ALL to analyse all coins, enter ACTIVE to analyse the markets of any coins you have in your lending account when the bot starts, these can be mixed.
analyseCurrencies = BTC,BTS,LTC,XMR,XRP,ETH
# Choose how long to keep market data. (In days) (1-365)
analyseMaxAge = 365
# Choose how often to record a market's rate. (In seconds.) (10-3600)
analyseUpdateInterval = 60
# Choose how aggressive to lend at based on a market's performance. (As a percentile of the market's rate.) (1-99)
# Recommendations: Conservative = 50, Moderate = 75, Aggressive = 90, Very Aggressive = 99
lendingStyle = 85

#Syntax: ["COIN:mindailyrate:maxactiveamount:maxtolend:maxpercenttolend:maxtolendrate",...]
#If maxactive amount is 0: stop lending this coin. in the future you'll be able to limit amount to be lent.
#If maxtolend is 0: check for maxpercenttolend.
#If maxpercenttolend is 0: 100% is going to be lent.
#If maxtolendrate is set to more than 0: the maxtolend or maxpercenttolend will be used when then rate is less or equal to the maxtolendrate. if set to 0 the bot will use the maxtolend or maxpercenttolend all the time.
# Please configure via the coinconfig line below OR individual coins in the [BTC], [CLAM], etc section. NOT both.
# coinconfig takes precedence
#coinconfig = ["BTC:0.18:1:0:0:0","CLAM:0.6:1:0:0:0"]

#This option creates a json log file instead of console output which includes the most recent status.
#Uncomment both jsonfile and jsonlogsize to enable.
#Keep this in the default location if you want to use the webserver.
#jsonfile = www/botlog.json

#Limits the amount of log lines to save.
#jsonlogsize = 200

#Enables a webserver for the www folder, in order to easily use the lendingbot.html with the .json log.
#startWebServer = true

#Customize the IP and port that the webserver is hosted on. Defaults to 0.0.0.0:8000
#0.0.0.0 will point to your default IP (Local IP on LAN as well as localhost), set to 127.0.0.1 if you want it to be only accessible by host computer.
#Do not set to a reserved port
#Advanced users only.
#customWebServerAddress = 0.0.0.0:8000

#The currency that the HTML Overview will present the earnings summary in.
#Options are BTC, USDT, ETH or anything as long as it has a direct BTC market. The default is BTC.
#outputCurrency = BTC

#Plugins allow extending Bot functionality with extra features.
#plugins = AccountStats

# Currencies can be configured here, or in the coinconfig. Coinconfig takes precedence.
#[BTC]
#minloansize = 0.01
#mindailyrate = 0.078
#maxactiveamount = 1
#maxtolend = 0
#maxpercenttolend = 0
#maxtolendrate = 0

[BTS]
minloansize = 0.001
mindailyrate = 0.01
maxactiveamount = 1
maxtolend = 0
maxpercenttolend = 0
maxtolendrate = 0

#[CLAM]
#minloansize = 1
#mindailyrate = 0.6
#maxactiveamount = 1
#maxtolend = 0
#maxpercenttolend = 0
#maxtolendrate = 0

**Comment by rnevet** [comment]
It seems like adding the exit would be a solution, otherwise not setting the minloansize below limit would be also a solution. Feel free to make a PR.

**Comment by mchl18** [comment]
I have already made a fix that I will commit asap. First PR on github woop woop

**Comment by rnevet** [comment]
The bot in any case would not allow setting lower minloansize and also auto adjusts on poloniex errors. It shouldn't hang though I agree.

**Comment by mchl18** [comment]
I don't know about the exit(1) but it seems to make an uneasy exit

**Comment by mchl18** [comment]
on what branch should that be?

**Comment by rnevet** [comment]
Hmm.. wait, I was mistaken, there is no need to exit on those cases, there is a fallback to the minimum limit.

**Comment by mchl18** [comment]
yes, but you are returning value, so it has to be set to min or max in the lines shown above, or am i mistaken? were else would be a fallback for such

**Comment by rnevet** [comment]
Hmm... sorry,.. I was confused, you are right, there isn't a fallback value right now. Thanks for the PR, I'll review it.

**Comment by mchl18** [comment]
No worries, i really love getting into the bot and python :)
You made a nice bot
