### ISSUE TITLE
Config fault tolerance

### ISSUE THREAD

**Issue by mchl18** [BitBotFactory/poloniexlendingbot#433]
Hey guys. In configuration.py there are some exits that I see as unnecessary.
They are caused by faulty configs but are also preventable by using default values. 
I downgraded ERRORS to WARNS.
I have made changes but cannot make a PR right now since I am sitting in a car for the next hours.
Will post it later

**Comment by rnevet** [comment]
I'm not sure that this is a needed change, config should be rigid imo when it comes to money.

**Comment by mchl18** [comment]
```
        except ValueError:
            if default_value is None:
                print "ERROR: [%s]-%s is not allowed to be left empty. Please check your config." % (category, option)
                exit(1)
            return default_value
    else:
        if default_value is None:
            print "ERROR: [%s]-%s is not allowed to be left unset. Please check your config." % (category, option)
            exit(1)
        return default_value
```
This is from Configuration.py:57-66
I would have handled these by using default value instead of quitting, as in #429.
Though I agree, the config should be rigid. I have been thinking about building an interface for the config, a kind of admin page for the bot frontend, that parses the configs and restarts the bot, so you can play around without terminal and cfg. There you could catch these errors before they land in the config and also unify the different coin config representations.  
I will do so on my fork. I think this issue can be closed then.

**Comment by rnevet** [comment]
@Evanito started to work on something for the config.

**Comment by mchl18** [comment]
would love to help

**Comment by Evanito** [comment]
Hey @mchl18 that snippet of code you pasted above handles scenarios where the setting is left unset where the setting is required. For most settings this will default to whatever the default is, but with options such as API Key, it is required to throw an error.

Do you see any other way to handle these? Maybe have more options that have default values?
