### ISSUE TITLE
New install, and getting lots of time outs

### ISSUE THREAD

**Issue by CptanPanic** [BitBotFactory/poloniexlendingbot#437]
So I have bot installed on a linux machine that doesn't have a VPN.  I am getting lots of things like error below.  I tried changing timeout to 60 seconds but it seems to have made it just take longer to correct.  Some messages do get through, but Anything I can do in this case?

```
"Error during summary notification: The read operation timed out Requesting returnActiveLoans
2017-08-05 12:30:08 Error: The read operation timed out Requesting returnActiveLoans
Timed out, will retry in 60.0sec
...
2017-08-05 12:34:59 Error: The read operation timed out Requesting returnTicker
Timed out, will retry in 60.0sec
".  

```

**Comment by tamaskan** [comment]
No, sadly thats normal for Poloniex. Just ignore the Errors.

**Comment by rnevet** [comment]
My timeout is on 90, but it seems that it doesn't change much.
