### ISSUE TITLE
Running webserver without JSON creates pointless setup

### ISSUE THREAD

**Issue by utdrmac** [BitBotFactory/poloniexlendingbot#438]
If you set `startWebServer = True` but don't uncomment `jsonfile` and `jsonlogsize`, then the webpage interface is pointless. There should be some exclusivity with these parameters or some sane defaults if you enable webserver but don't uncomment the other two.

**Comment by mchl18** [comment]
The wepage could need a general overhaul and catch such cases

**Comment by utdrmac** [comment]
The webpage need not make this decision; the code should BEFORE even starting the webserver. A) fix code to make these parameters mutually exclusive or B) if startWebServer=True and jsonfile=UNDEF and jsonlogsize=UDEF (meaning still commented in config) then use some defaults.

**Comment by rnevet** [comment]
@utdrmac make it so if you have the time. 👍
