### ISSUE TITLE
Bcash

### ISSUE THREAD

**Issue by coulterj** [BitBotFactory/poloniexlendingbot#442]
In the config for Bitfinex, it looks like there is no support for BCH.  Can I just add BCH to the supported currencies and market analysis sections?

**Comment by tamaskan** [comment]
BCH is not yet implemented https://poloniex.com/press-releases/2017.08.03-Bitcoin-Cash-Update/

**Comment by coulterj** [comment]
On Poloniex correct.  On Bitfinex it is supported.

**Comment by coulterj** [comment]
It does look like you can add BCH to both sections.

**Comment by utdrmac** [comment]
@coulterj Close the issue if all works please.
