### ISSUE TITLE
Systemctl is broken with finex update

### ISSUE THREAD

**Issue by rstormsf** [BitBotFactory/poloniexlendingbot#443]
```

Aug 09 22:04:31 ip-172-31-7-110 systemd[1]: pololendingbot.service: Main process exited, code=exited, status=
Aug 09 22:04:31 ip-172-31-7-110 systemd[1]: pololendingbot.service: Unit entered failed state.
Aug 09 22:04:31 ip-172-31-7-110 systemd[1]: pololendingbot.service: Failed with result 'exit-code'.
```

**Comment by rnevet** [comment]
Did you install the new dependencies? 
http://poloniexlendingbot.readthedocs.io/en/latest/installation.html#prerequisites
requests (HTTPS communication)
pytz (Timezone calculations)

**Comment by Evanito** [comment]
@rnevet We should move those to the "Needed" section under prerequisites.

**Comment by rstormsf** [comment]
Manual execution works fine.
Yes, I did install the dependencies.
