### ISSUE TITLE
bitfinex lending error message

### ISSUE THREAD

**Issue by ououmin** [BitBotFactory/poloniexlendingbot#448]
2017-08-11 13:32:01 Error USD_EOS
Traceback (most recent call last):
  File "/home/someone/poloniexlendingbot/lendingbot.py", line 137, in <module>
    Lending.lend_all()
  File "/home/someone/poloniexlendingbot/modules/Lending.py", line 234, in lend_all
    lend_all()
  File "/home/someone/poloniexlendingbot/modules/Lending.py", line 232, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/home/someone/poloniexlendingbot/modules/Lending.py", line 429, in lend_cur
    raise msg
KeyError: u'USD_EOS'

Unhandled error, please open a Github issue so we can fix it!

Error during new loans notification: API Error 400: {"message":"Nonce is too small."} Requesting https://api.bitfinex.com/v1/credits

Error during new loans notification: API Error 400: {"message":"Nonce is too small."} Requesting https://api.bitfinex.com/v1/credits

------------------------------------------------------

I don't know what is wrong.

How can i fix it?

**Comment by mahiso** [comment]
> "Nonce is too small."

Please create a new API key on Bitfinex. The nonce in one request must always be greater than the nonce in last request. Therefore it is not possible to use one API key in more than one application.

**Comment by ououmin** [comment]
Thanks mahiso for answer.

How about earlier error message?
"KeyError: u'USD_EOS'" 
What does that mean?
I saw that message many times.

**Comment by TekMuzik** [comment]
I get this message periodically. Seems to be something from Bitfinex side. You can leave the bot running and it usually resumes normal activity within 10 minutes or so. Hopefully, a fix can be found in a later release, but at least for now it is not a breaking error.

**Comment by ououmin** [comment]
You are right TekMuzik.
It's not serious error and the bot works, anyway.
Thanks.

**Comment by rnevet** [comment]
Key error is handled in issue #447
