### ISSUE TITLE
Bitfinex lending hangup

### ISSUE THREAD

**Issue by AlexEremeenkov** [BitBotFactory/poloniexlendingbot#449]
I used bitfinex lending for a few days and noted strange problem.
After some period of time (4-24 hours of work) bot is hang up and don't show any activity.
HTML page shows old activity time and console log don't show rare periodical errors from the exchange.
Also, I don't see any requests to exchange from bot side.

At same time polo lending work more stable.
Unfortunately I don't know how to provide more details because it just hangs and I don't know how to debug it.
Is it any suggestion for trace this problem?

**Comment by AlexEremeenkov** [comment]
it seems to me, this piece of code in Bitfinex.py could be reason for the problem:
```
            if (request == 'get'):
                r = requests.get(self.url + command)
            else:
                r = requests.post(self.url + command, headers=payload, verify=verify)
```

According to requests documentation, timeout required.
Now I test bot with such source change:
```
            if (request == 'get'):
                r = requests.get(self.url + command, timeout=30)
            else:
                r = requests.post(self.url + command, headers=payload, verify=verify, timeout=30)
```

**Comment by rnevet** [comment]
As far as I can see, timeout isn't a required parameter.

**Comment by rnevet** [comment]
You are correct, without a timeout parameter the bot can hang.
However we have a timeout in the config and should use it.
