### ISSUE TITLE
Bug in Earning Today

### ISSUE THREAD

**Issue by CyberBaby** [BitBotFactory/poloniexlendingbot#465]
In AccountStats.py, the checking for the rowcount is not necessary.

Just updated as below and it works now.

# Today's earnings
        cursor = self.db.execute(DB_GET_TODAYS_EARNINGS)        
        for row in cursor:
			output += self.format_value(row[0]) + ' ' + str(row[1]) + ' Today\n'
			if row[1] not in self.earnings:
				self.earnings[row[1]] = {}
			self.earnings[row[1]]['todayEarnings'] = row[0]      
        cursor.close()

**Comment by utdrmac** [comment]
If you do this, then you don't get ANY output for "Today". This was not the goal. The goal was to have 'None' displayed if there was none instead of just omitting it completely.

**Comment by utdrmac** [comment]
Technically, this is the same issue as 'Yesterday' and 'Total' but I wanted to visibly see 'None' rather than have nothing printed.

**Comment by CyberBaby** [comment]
I got the same query result as i performed in the DB for my code. What do you mean by any output? I thought it is printing the query result of

DB_GET_TODAYS_EARNINGS = "SELECT sum(earned) as total_earned, currency FROM 'history' " \
                     "WHERE close > datetime('now','start of day') GROUP BY currency"

**Comment by rnevet** [comment]
@CyberBaby, This isn't a Bug, you are suggesting a code optimization.
As utdrmac explained the rowcount check is used to in order to print "None Today" in case no earnings are found.

**Comment by CyberBaby** [comment]
I see what you mean. But i got always -1 in cursor.rowcount, in result, i got None Today always. Not too familiar with sqlite query. So i made the changes like yesterday or total.
Running with Python 2.7.9.

**Comment by rnevet** [comment]
Yes, it really depends if you want to see "None Today" - no earnings today, or not see anything at all.

**Comment by CyberBaby** [comment]
Here is the fix. 

# Today's earnings
        cursor = self.db.execute(DB_GET_TODAYS_EARNINGS)
        row = cursor.fetchone()                
        
        if row is not None:           
			output += self.format_value(row[0]) + ' ' + str(row[1]) + ' Today\n'
			if row[1] not in self.earnings:
				self.earnings[row[1]] = {}
			self.earnings[row[1]]['todayEarnings'] = row[0]
        else:
            output += 'None Today\n'
        cursor.close()

**Comment by rnevet** [comment]
@CyberBaby Why is this better?

**Comment by rnevet** [comment]
@utdrmac According to what CyberBaby poseted, it could be that you'll never get a rowcount from a SELECT query.

**Comment by CyberBaby** [comment]
@rnevet Right. For my account, I do have earnings today when I run the query in the DB. And then I found out that the rowcount is always return -1 in my running instance which in result getting 'None Today' always. Not sure if this happens on other running environment.

**Comment by utdrmac** [comment]
Ok. I understand what he's saying. Let me test cause I pulled the rowcount check code from another python script.

**Comment by utdrmac** [comment]
@CyberBaby Can you make PR please? Thanks!

**Comment by utdrmac** [comment]
I'm working on PR right now

**Comment by CyberBaby** [comment]
@utdrmac Thanks!
