### ISSUE TITLE
Error 'exceptions.ValueError' object has no attribute 'code'

### ISSUE THREAD

**Issue by mike4001** [BitBotFactory/poloniexlendingbot#471]
Hi

My bot stopped working this night:

Web-Interface says:

Error 'exceptions.ValueError' object has no attribute 'code'

error.txt says:

Traceback (most recent call last):
  File "lendingbot.py", line 136, in <module>
    if notify_conf['notify_caught_exception']:
KeyError: 'notify_caught_exception'
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

**Comment by mike4001** [comment]
I also have a second instance of the bot running which also just crashed ..

Web-Interface says:

Error local variable 'ticker' referenced before assignment

error.txt says:

Traceback (most recent call last):
  File "lendingbot.py", line 136, in <module>
    if notify_conf['notify_caught_exception']:
KeyError: 'notify_caught_exception'

**Comment by utdrmac** [comment]
@mike4001 Are you running Polo or Bitfinex? I've received the 'ticker' error before on Bitfinex.

**Comment by mike4001** [comment]
Sorry, should have added the information

The first error (exceptions.ValueError) is from the bot running on Poloniex

The second error (ticker) is from the bot running on Bitfinex

**Comment by mike4001** [comment]
OK, my Bitfinex Bot is hanging again

Same Error as above: Error local variable 'ticker' referenced before assignment

**Comment by rnevet** [comment]
Please make sure your not is updated, hanging is most likely fixed already. (Timeout added)

**Comment by mike4001** [comment]
My bots are up-to-date.

I now had 4 cases from my Bitfinex-Bot getting the 'ticker' error and according to the web interface he stopped working. Though the webserver was still running but the last entry was said 'ticker' error and it did no update after that.

**Comment by utdrmac** [comment]
I think @mahiso needs to be aware of this 'ticker' issue as it comes from his Bitfinex code.

**Comment by utdrmac** [comment]
Oddly, I've received this error twice in the past 12hrs but my bot did not crash. it accepted the error and continued on. I'm curious as to why yours crashed/halted.

**Comment by mahiso** [comment]
I will rework the method. Eta next week.

**Comment by Evanito** [comment]
Fix has been pushed (Just getting to old issues)
Comments again if not fixed
