### ISSUE TITLE
I have a minor question about message 'Not enough offers in response'

### ISSUE THREAD

**Issue by ououmin** [BitBotFactory/poloniexlendingbot#475]
> 'USD:Not enough offers in response, adjusting request limit to 200'
> 'USD:Not enough offers in response, adjusting request limit to 300'

Is it about gapbottom/gaptop value?
I saw that messages often but have no idea what it means.

**Comment by rnevet** [comment]
It's about the bot not finding the gaps in the offers list he asks for (~100 offers), so it automatically increases this limit.

**Comment by ououmin** [comment]
Oh, I see. Thanks.
