### ISSUE TITLE
Need to add OMG and XRP as a valid currencies in Bitfinex

### ISSUE THREAD

**Issue by JCBauza** [BitBotFactory/poloniexlendingbot#480]
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please make a Github issue so we can fix it. Otherwise, you can safely ignore it. Error: OMG is not a valid currency, must be one of ['USD', 'BTC', 'ETH', 'ETC', 'ZEC', 'XMR', 'LTC', 'DSH', 'IOT', 'EOS', 'BCH']

**Comment by JCBauza** [comment]
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please make a Github issue so we can fix it. Otherwise, you can safely ignore it. Error: XRP is not a valid currency, must be one of ['USD', 'BTC', 'ETH', 'ETC', 'ZEC', 'XMR', 'LTC', 'DSH', 'IOT', 'EOS', 'BCH']

**Comment by JCBauza** [comment]
Just need to change the line on default.cfg to include it... but not sure how to do the pull request:

[BITFINEX]
# Full list of supported currencies
all_currencies = USD,BTC,ETH,ETC,ZEC,XMR,LTC,DSH,IOT,EOS,BCH,XRP,OMG

**Comment by utdrmac** [comment]
@JCBauza you need to first fork this repo to your own github account. Then, clone your copy into a new location on your computer, create a branch called "issue_480" (for example). Switch to that branch. Make whatever changes to your copy. Commit/push the change to your branch. Visit the URL for your fork. it will say something like 'recently pushed this branch. want to make a PR?' Submit the PR between `BitBotFactory/poloniexlendingbot:master` and `myaccount/poloniexlendingbot:issue_480`

**Comment by rnevet** [comment]
Actually it's much simpler,
Open the file on Github: https://github.com/BitBotFactory/poloniexlendingbot/blob/master/default.cfg.example
Select edit on the top right, make your changes, it will automatically create a branch and a PR. :) 

This is sufficient for simple changes.

**Comment by JCBauza** [comment]
Awesome, thx guys!
