### ISSUE TITLE
[BitFinex] WARN: Incorrect coin entered for transferCurrencies: ___

### ISSUE THREAD

**Issue by JCBauza** [BitBotFactory/poloniexlendingbot#483]
Without any serious customization when enabling the transferablecurrencies section I get the following error messages. This happens even if I use "transferableCurrencies = ALL"

WARN: Incorrect coin entered for transferCurrencies: USD
WARN: Incorrect coin entered for transferCurrencies: BCH
WARN: Incorrect coin entered for transferCurrencies: XRP
WARN: Incorrect coin entered for transferCurrencies: XMR
WARN: Incorrect coin entered for transferCurrencies: OMG
WARN: Incorrect coin entered for transferCurrencies: EOS
WARN: Incorrect coin entered for transferCurrencies: ZEC

**Comment by laxdog** [comment]
Polo is returning a dict with keys of the currencies, bitfinex is returning a json list. 

So we just need to change the bitfinex return to match the polo one. I can't see the return_balances being called any where else, so it shouldn't break anything.

**Comment by laxdog** [comment]
Actually, maybe that's not the case...

**Comment by laxdog** [comment]
OK, I see what's wrong now. I'll raise a PR.

**Comment by laxdog** [comment]
Can you test https://github.com/BitBotFactory/poloniexlendingbot/pull/540 @JCBauza ?

**Comment by JCBauza** [comment]
I just deployed the changes on my computer... besides the error not showing up during launch how can I test this?

**Comment by laxdog** [comment]
Well that's a start at least. 

You could put some coins in your exchange account and make sure they're transferred. Though I've tested that myself and it looks to be fine.

**Comment by JCBauza** [comment]
It worked for some in my case, but not all. EOS and OMG didn't transfer. I had set transferableCurrencies = ALL , so they should had been taken care of.

**Comment by laxdog** [comment]
Do you have them in `all_currencies` ?

**Comment by JCBauza** [comment]
yes, this is what I have: 
all_currencies = USD,BTC,BCH,ETH,XRP,IOT,XMR,LTC,OMG,ETC,EOS,DSH,ZEC,NEO,SAN
