### ISSUE TITLE
[BitFinex] EOS lending only 5.50% of all available

### ISSUE THREAD

**Issue by JCBauza** [BitBotFactory/poloniexlendingbot#486]
I am using the default config and haven't set up any max or mins, and somehow EOS is the only currency were I see a limit of how much I can lend:

EOS1 EOS = 1.41 USD | Lent 91.0584 of 1655.4278 (5.50%) TotalLent 91.0584 of 91.0584 (100.00%) Lendable | 0.00900% Day Avg.0.00042% Day Eff.0.15% Year0.16% Year Comp.
-- | -- | --

**Comment by utdrmac** [comment]
As the code is the same for all coins, I suspect this something coming from BitFinex. Do you have the bot running in a screen/tmux so you can see all the debug output?

**Comment by JCBauza** [comment]
Updated the code and restarted the program a few hours ago... now it shows like the rest of the coins so not sure what happened and can't reproduce it now. If it happens again I'll post the console output here.

**Comment by utdrmac** [comment]
Was there a recent transfer of coins in to the account? I noticed a lag in the bot updating when I transfered in some new coins but it eventually updated itself and now lends 100% of all my coins.

**Comment by JCBauza** [comment]
not in the case of EOS. I have only deposited ETH, BTC and Dash. All the EOS I bought on the platform and I was lending them already.

**Comment by JCBauza** [comment]
I am going to close it as it hasn't happened again.
