### ISSUE TITLE
Plugins should return true/false on their init

### ISSUE THREAD

**Issue by utdrmac** [BitBotFactory/poloniexlendingbot#489]
When a plugin is initialized, it should return true/false to indicate to the pluginManage that it successfully initialized. If false, do not add it to the plugins array.

**Comment by rnevet** [comment]
As we have 1 plugin so far, what's the need?  
Theoretically a plugin can manage this logic internally, no?

**Comment by utdrmac** [comment]
I'm developing another plugin. That'll make 2 :)

I guess, technically, yes, a plugin can have a `self.enabled` and check it every time.

**Comment by rnevet** [comment]
I suggest you make a PR for the improvement of the PluginManager.
