### ISSUE TITLE
Bottom_rate is not being set to the first rate in the case of no_gap

### ISSUE THREAD

**Issue by bgits** [BitBotFactory/poloniexlendingbot#492]
https://github.com/BitBotFactory/poloniexlendingbot/blob/master/modules/Lending.py#L280

**Comment by utdrmac** [comment]
Can you provide some more description to this bug?

**Comment by bgits** [comment]
Without this change it's currently not possible to have the bot set at the lowest rate. Instead it will offer above the first 100 orders even when there is no gap.
