### ISSUE TITLE
Pythonanywhere - anything but perfect

### ISSUE THREAD

**Issue by gonzzza007** [BitBotFactory/poloniexlendingbot#508]
Not really the technical issue, but saying that Pythonanywhere (free account) is perfect - is very misleading.

I had to do a heavy config optimizing, otherwise the script uses allowed 100% of processor time and is put in "tarpit".
I disabled the web interface, left only one currency, increased sleeptimeactive, sleeptimeinactive intervals, disabled Auto-transfer of funds and shorten the history to be able to fit into these 100%...

And even now my script has to be manually started every day. It just quits for no reason! I think this is a "limitation" of free account. Paid accounts are promised to be much better :)

At least you have to warn about these issues and not call it a "perfect place" for the bot. If only it's not a paid advertisement for them...

**Comment by rnevet** [comment]
I agree pythonanywhere has many other issues, I'll remove the comment.
