### ISSUE TITLE
Bitfinex Error - API Error 400

### ISSUE THREAD

**Issue by mike4001** [BitBotFactory/poloniexlendingbot#509]
Hi,

I am now getting the error below for Bitfinex. It's going this way for several hours now. Bot is non functional.

Error API Error 400: <html>
<head><title>400 Request Header Or Cookie Too Large</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>Request Header Or Cookie Too Large</center>
<hr><center>cloudflare-nginx</center>
</body>
</html>
Requesting https://api.bitfinex.com/v1/offer/new

**Comment by rnevet** [comment]
This was reported: https://github.com/BitBotFactory/poloniexlendingbot/issues/444

You can test the proposed solution there.
