### ISSUE TITLE
Backtesting?

### ISSUE THREAD

**Issue by chriscrutt** [BitBotFactory/poloniexlendingbot#519]
I know there is a Dry Run option, but if I am not mistaken that runs a simulation in current time. Would there be a possible way to look at past Poloniex/Bitfinex lend orders and such to see how the bot would've reacted? It could do this using the API and looking at the CSVs

Just an idea! 

I love how much time and effort you put into this project, thank you so much

**Comment by laxdog** [comment]
The new method of recording data uses sqlite db files. 

There are multiple ways to do this, but none of them trivial. 

I'd also love to see it as it would be a great way to add new market analysis functions, but I don't think it's going to happen any time soon.

**Comment by chriscrutt** [comment]
Label as discussion?

**Comment by rnevet** [comment]
@chriscrutt did you close the ticket on purpose?
