### ISSUE TITLE
How to Run an online server no port apache2 (way 2 coming soon)

### ISSUE THREAD

**Issue by chriscrutt** [BitBotFactory/poloniexlendingbot#523]
This tutorial is for *NIX style machines, I did this with my Raspberry Pi running Jessie

1. First navigate to the [installation guide](http://poloniexlendingbot.readthedocs.io/en/latest/installation.html) for the bot itself and install prerequisits.
2. then clone the bot to your favorite folder, such as 1/home/<username>/1
3. edit the default.cfg file however you like, but make sure to keep it 0.0.0.0 and port 8000 for the webserver
4. `sudo apt-get install tmux`
5. `cd /home/<username>/poloniexlendingbot`
6. `tmux`
7. enter `python lendingbot.py`, this should start running the bot.
8. press CRL+B and then press D to detach the instance of tmux, which keeps it running in background. Also, if you need to go back to the bot instance or etc, do `tmux attach`
9. find your system's IP address with `hostname -I` and look up "hostname":8000 on a browser to make sure the bot is working (example: 192.168.1.34:8000)
10. install apache2 with `sudo apt-get install apache2 php5 libapache2-mod-php5`
11. restart apache2 with `sudo service apache2 restart`
12. if you search your hostname without the "8000" (just 192.168.1.34), it should bring you to the default apache2 page
13. We want to see our bot web server without having to go to the 8000 port (trust.) so we `cd /etc/apache2`
14. `sudo nano apache2.conf`, find where this is:

    <Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted

15. Then change the `/var/www/` to where the www folder is for our bot, usually `/home/<username>/poloniexlendingbot/www/`
16. CTL + X and save
17. `cd sites-available` and `sudo nano 000-default.conf`
18. Find where it says `DocumentRoot /var/www/html` and replace with `DocumentRoot /home/<username>/poloniexlendingbot/www` notice no slash after the www
19. `sudo nano default-ssl.conf` and find `DocumentRoot /var/www/html` again and replace with `DocumentRoot /home/<username>/poloniexlendingbot/www`
20. CTL + X and save
21. `sudo service apache2 restart` and navigate to your hostname and it should be up! From here if you own a domain you can point it to your hostname or other stuff. YAY!

**Comment by utdrmac** [comment]
Or you could just change `customWebServerPort` to be 80 and not mess with installing apache at all. What's the difference? This apache method seems to be amazing over-kill.

**Comment by utdrmac** [comment]
Plus, if you run multiple instances of the bot, this won't work because the apache isolates you to a single instance (ie: folder) of the bot.

**Comment by chriscrutt** [comment]
Well damn

**Comment by chriscrutt** [comment]
Way 2:

In default.cfg, change your port from 8000 to 80

**Comment by utdrmac** [comment]
Sorry for bursting your bubble. I've got a free dns from duckdns.org so I can access my bots from home using that :8000 and :8001 It's just a port. Your browser just hides the :80 from you. The bot still serves up HTTP/1.0 qualified traffic.

**Comment by chriscrutt** [comment]
@utdrmac duckdns.org does what exactly, points a subdomain of duckdns.org to your IP? so instead of looking up 192.168.1.34:8000 you could look up lendingbot.duckdns.org?

My second method was using a ftp server and uploading the poloniexlendingbot/www folder to a free domain hosting website.

**Comment by utdrmac** [comment]
Well, their free subdomain services don't do port redirection. If I wanted port 80, I would just set the bot to use port 80 and that would be fine; no apache needed. But as I run multiple bots, I have to use multiple ports.

If you upload to a hosting website, that might not work as the JSON/AJAX could have cross-domain security issues.

What exactly are you trying to accomplish with this "issue"?

**Comment by chriscrutt** [comment]
Could you label this discussion please? sorry about that.
