### ISSUE TITLE
easy back to dashboard

### ISSUE THREAD

**Issue by chriscrutt** [BitBotFactory/poloniexlendingbot#526]
please label enhancements/discussion

I didn't want to do an entire pull request for this, but i thought it might look more aesthetically pleasing if we took off the blue "dashboard" link at the bottom of charts.html and put it top right.

It would look like this:

![charts](https://user-images.githubusercontent.com/6835463/30671011-b260ccac-9e19-11e7-8523-02fde7bfa06b.png)

here is my code: 

[charts.txt](https://github.com/BitBotFactory/poloniexlendingbot/files/1319449/charts.txt)

**Comment by rnevet** [comment]
A PR would be nice. :)

**Comment by utdrmac** [comment]
I can do a PR for this later today.
