### ISSUE TITLE
[Bug] Error: Rates must be a Pandas DataFrame

### ISSUE THREAD

**Issue by TVilaboa** [BitBotFactory/poloniexlendingbot#527]
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame

It happens every few minutes and it never stops. I'm using the last commit version. How can i provide more debug info?

[cfg.txt](https://github.com/BitBotFactory/poloniexlendingbot/files/1321338/cfg.txt)

**Comment by TVilaboa** [comment]
Changed exception to `raise ValueError("Rates must be a Pandas DataFrame. Rates: {0}".format(json.dumps(rates, default=lambda o: o.__dict__)))` and got
> WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Rates: []

It seems that rates is empty. I will try deleting market_data files.

**Comment by TVilaboa** [comment]
Changed to ` raise ValueError("Rates must be a Pandas DataFrame. Cur: {0} . Method: {1} . Rates: {2}".format(cur,method,json.dumps(rates, default=lambda o: o.__dict__)))`

> WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Cur: BTS . Method: MACD . Rates: []
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Cur: FCT . Method: MACD . Rates: []
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Cur: BTS . Method: MACD . Rates: []
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Cur: FCT . Method: MACD . Rates: []
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Cur: BTS . Method: MACD . Rates: []
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Cur: DOGE . Method: MACD . Rates: []
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Cur: FCT . Method: MACD . Rates: []
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Cur: DOGE . Method: MACD . Rates: []
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Cur: FCT . Method: MACD . Rates: []
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Cur: DOGE . Method: MACD . Rates: []
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Cur: FCT . Method: MACD . Rates: []
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Cur: DOGE . Method: MACD . Rates: []
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Cur: FCT . Method: MACD . Rates: []
WARN: Exception found when analysing markets, if this happens for more than a couple minutes please create a Github issue so we can fix it. Otherwise, you can ignore it. Error: Rates must be a Pandas DataFrame. Cur: DOGE . Method: MACD . Rates: []

I'm using MACD for Daily_min  and i have 11 different currencies but i have `analyseCurrencies = BTC,ETH` to lower CPU load, requests, etc. Is there a way configure Daily_min for each currency or default to percentile if rates are empty?

**Comment by laxdog** [comment]
Hey @TVilaboa config looks fine. 

Though is that the config that gave the output in the last comment? There shouldn't be all those currencies if so. 

Can you also send the output of:

```
pip freeze
ls -lrtha poloniexlendingbot
ls -lrtha poloniexlendingbot/market_data
```

**Comment by laxdog** [comment]
Also, can you turn on the `ma_debug_log` option, it should give more information.

**Comment by laxdog** [comment]
OK, I think I see what's happening. Putting a fix in now.

**Comment by laxdog** [comment]
@TVilaboa Can you test the fix on MA_min_fix?

I'll raise a PR for it now, to be merged pending your testing.

**Comment by TVilaboa** [comment]
Got this error:
> Traceback (most recent call last):
  File "C:\LendingBot-Testing\poloniexlendingbot\lendingbot.py", line 80, in <module>
    Lending.init(Config, api, log, Data, MaxToLend, dry_run, analysis, notify_conf)
  File "C:\LendingBot-Testing\poloniexlendingbot\modules\Lending.py", line 85, in init
    currencies_to_analyse = config.get_currencies_list('analyseCurrencies', 'MarketAnalysis')
NameError: global name 'config' is not defined

Fixed changing 
` currencies_to_analyse = config.get_currencies_list('analyseCurrencies', 'MarketAnalysis')` 
to
 ` currencies_to_analyse = Config.get_currencies_list('analyseCurrencies', 'MarketAnalysis')`  (Capital C in Config)

Everything working perfectly! No more error messages. Thanks!

**Comment by TVilaboa** [comment]
#529

**Comment by TVilaboa** [comment]
#529

**Comment by laxdog** [comment]
OK, thanks. I couldn't test it as I was on the train when I made the commit. 

I'll fix that now. Thanks!

**Comment by TVilaboa** [comment]
It appeared only after i let it running all night. I suppose its related to this issue. I will try to provide more info as soon as i can.

> Unhandled error, please open a Github issue so we can fix it!
> 2017-09-22 10:19:18 Error list index out of range
> Traceback (most recent call last):
>   File "C:\LendingBot\poloniexlendingbot\lendingbot.py", line 94, in <module>
>     Lending.lend_all()
>   File "C:\LendingBot\poloniexlendingbot\modules\Lending.py", line 246, in lend_all
>     usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
>   File "C:\LendingBot\poloniexlendingbot\modules\Lending.py", line 417, in lend_cur
>     orders = construct_orders(active_cur, active_bal, active_cur_total_balance, ticker)  # Build all potential orders
>   File "C:\LendingBot\poloniexlendingbot\modules\Lending.py", line 318, in construct_orders
>     top_rate, bottom_rate = get_gap_mode_rates(cur, cur_active_bal, cur_total_balance, ticker)
>   File "C:\LendingBot\poloniexlendingbot\modules\Lending.py", line 370, in get_gap_mode_rates
>     bottom_rate = get_gap_rate(cur, bottom_depth, order_book, cur_total_balance, True)
>   File "C:\LendingBot\poloniexlendingbot\modules\Lending.py", line 305, in get_gap_rate
>     return Decimal(order_book['rates'][i])
> IndexError: list index out of range
> 
> Unhandled error, please open a Github issue so we can fix it!

**Comment by TVilaboa** [comment]
> DEBUG:get_gap_rate: Cur: BTS - Gap: 10422094.84106305367378843147 - VolumesLength: 472 - RatesLength: 472 - i: 472

**Comment by TVilaboa** [comment]
>  DEBUG:get_gap_rate: Cur: BTS - Gap: 10432968.17944705268648930621 - VolumesLength: 467 - RatesLength: 467 - i: 467 - gap_sum: 10436880.1066 - gap_expected: 10432968.17944705268648930621
> 
> 
> DEBUG:get_gap_rate: Cur: BTS - Gap: 10346611.48473874806001034661 - VolumesLength: 457 - RatesLength: 457 - i: 457 - gap_sum: 10434789.538 - gap_expected: 10346611.48473874806001034661
> 
> 
> DEBUG:get_gap_rate: Cur: BTS - Gap: 10368066.35562467599792638673 - VolumesLength: 468 - RatesLength: 468 - i: 468 - gap_sum: 10444225.1029 - gap_expected: 10368066.35562467599792638673

**Comment by TVilaboa** [comment]
@laxdog
