### ISSUE TITLE
convert to other time zones?

### ISSUE THREAD

**Issue by chriscrutt** [BitBotFactory/poloniexlendingbot#530]
label discussion/enhancement please

I am in LA and the timezone here is currently September 21, 21:00 (PDT)

on the bot server and in `botlog.json` it says (at current time cause it updates obviously) that it is September 22, 04:00 (GMT). Is there a way to convert the timezone in `botlog.json` and `lendingbot.html`? Maybe using JS - timezoneJS.Date? IDK too much but just an option open to discussion about. I know you have your own lives haha.

**Comment by rnevet** [comment]
I think all you need to do is set the timezone of your server.

**Comment by chriscrutt** [comment]
you mean see if my machine has the correct time zone?

**Comment by laxdog** [comment]
The issue is almost definitely on the server. You should just be able to fix it there. 

Are you running inside docker? It can also mess about with the TZ.

**Comment by chriscrutt** [comment]
no you were correct i believe, let me update my time and see if it changes the server, then ill close this

**Comment by chriscrutt** [comment]
yay it worked
