### ISSUE TITLE
Bitfinex has no max loan rate

### ISSUE THREAD

**Issue by chriscrutt** [BitBotFactory/poloniexlendingbot#532]
Question

Why is the lend rate capped at 5? What if the rate goes over 5 and I would like the bot to go higher? What would happen if i changed `lending.py` and set the range of min and max rate from `0.003, 5` to `0.003, 1000`? Would it screw up the bot?

**Comment by Evanito** [comment]
Poloniex will not allow lends that go over a 5% daily interest rate.

If Bitfinex allows a higher rate, we should change it.

**Comment by chriscrutt** [comment]
https://www.bfxdata.com/swaphistory/usd

Select 'all'

**Comment by uzitgc** [comment]
isnt 5 the maximum lending rate on Polo?

**Comment by chriscrutt** [comment]
On Bitfinex there no limit, that's why I gave that link, so you could see for your own eyes it goes above 5%

**Comment by chriscrutt** [comment]
![img_6834](https://user-images.githubusercontent.com/6835463/30762986-16e6e7a8-9f99-11e7-8594-8ac4c748ad93.PNG)
![img_6835](https://user-images.githubusercontent.com/6835463/30762987-16eaabc2-9f99-11e7-9ef1-7948567e5434.PNG)

**Comment by chriscrutt** [comment]
https://github.com/BitBotFactory/poloniexlendingbot/pull/534
