### ISSUE TITLE
Moving files around...

### ISSUE THREAD

**Issue by chriscrutt** [BitBotFactory/poloniexlendingbot#537]
Discussion/Enhancement

I saw the .html after all my files in the browser. I know that if you put an `index.html` file in a folder the folder will display the folder name (i.e. "charts") instead of chart.html

In the process of doing this however, I soon realized that everything has a specific place and if I were to move one thing I'd have to either move everything else, or adjust a lot of the code in order for it to work. 

Is having folders instead of .html an option in the future?

**Comment by utdrmac** [comment]
That's only true for apache (not displaying .html for index.html). There would have to be code written into the bot to search for an index.html inside each folder and display it.

You could actually just modify the existing code to search for <anything>.html So if you enter "/charts" the code would search for charts.html and return that.

What's wrong with seeing the .html extension? Never bothered me as it's pretty standard.

**Comment by chriscrutt** [comment]
Ah, I'm using an online host and using cron to auto send the files via FTP (this is all that's available for free). I assume they use apache or the search code as folders display the index.html code within them.

I just thought it looked more minimal and aesthetically pleasing without the .html tag. No worries, I know y'all have a lot on your plate and you have a life lol. I just wanted to know if there was an easy "solution". Thanks for the incite!

**Comment by utdrmac** [comment]
@chriscrutt Are you using the FTP method so you can access status from anywhere? I run mine at home and just port-forward. Allows me to access stats of both my bots from anywhere in the world. No hosting provider needed.

By the way, "insight" not "incite". The former is "thanks for the information" while the later is "to stir up violent behavior (incite a riot)"

**Comment by chriscrutt** [comment]
I wanted to use another hosting service so **my** internet wouldn't be bogged down or DDossed.
