### ISSUE TITLE
Bitfinex max daily lend rate

### ISSUE THREAD

**Issue by chriscrutt** [BitBotFactory/poloniexlendingbot#538]
I had previously said in an issue that Bitfinex has no daily lend rate cap. As I explored the bot and put in an arbitrarily large percent as the max daily lend rate (like 10000000) the Bitfinex API sent back that their max daily lend rate is 7%.

I know right now we have it set that 5% is the max rate, which is true for Poloniex, but not Bitfinex.

This is what I changed in my modules/Lending.py (seemed to do the trick):

    min_daily_rate = Decimal(Config.get("BOT", "mindailyrate", None, 0.003, 7)) / 100
    max_daily_rate = Decimal(Config.get("BOT", "maxdailyrate", None, 0.003, 7)) / 100

Would there be a way, like what you did here:

    if exchange == 'BITFINEX':
        xdays = str(Config.get("BOT", "xdays", None, 2, 30))
    else:
        xdays = str(Config.get("BOT", "xdays", None, 2, 60))

To do this?:

    if exchange == 'BITFINEX':
        min_daily_rate = Decimal(Config.get("BOT", "mindailyrate", None, 0.003, 7)) / 100
    else:
        min_daily_rate = Decimal(Config.get("BOT", "mindailyrate", None, 0.003, 5)) / 100

    if exchange == 'BITFINEX':
        max_daily_rate = Decimal(Config.get("BOT", "maxdailyrate", None, 0.003, 7)) / 100    
    else:
        max_daily_rate = Decimal(Config.get("BOT", "maxdailyrate", None, 0.003, 5)) / 100

The funny part is, is when I check the Bitfinex margin funding book I see there are rates over 1000% daily. My funding period ends in a day and I will attempt to lend for an arbitrarily large rate through the Bitfinex GUI. Tell ya then!

**Comment by laxdog** [comment]
If it turns out it can be whatever you want, then yea. Raise a PR.

It probably does need a cap on it, why did you choose 7?

**Comment by chriscrutt** [comment]
maybe there was something hidden in the coding I didn't see, but it told me that 7 was the max according to the Bitfinex API, here let me try to replicate what I did.... I'll see if I can show you.

**Comment by chriscrutt** [comment]
<img width="1680" alt="screen shot 2017-09-27 at 12 14 04 am" src="https://user-images.githubusercontent.com/6835463/30900432-d505243e-a318-11e7-8d1c-7e7267b560ea.png">
 sorry I guess 7% is the max for Bitfinex

**Comment by chriscrutt** [comment]
PR #547
