### ISSUE TITLE
nonce too small and etc api error

### ISSUE THREAD

**Issue by chriscrutt** [BitBotFactory/poloniexlendingbot#541]
I have the bot running on my Raspi and it works great.

I was experimenting with my Mac and I notice that when I run the bot I frequently receive:

    2017-09-26 15:26:53 Error API Error 400: {"message":"Nonce is too small."} Requesting https://api.bitfinex.com/v1/credits
    Caught API Error 400: {"message":"Nonce is too small."} Requesting https://api.bitfinex.com/v1/credits reading from exchange API, ignoring.

it doesn't seem to bother the bot too much, sometimes the data goes away or it takes longer to update than normal. I also receive this:

    2017-09-26 15:25:45 Error API Error 520: The web server reported a bad gateway or gateway timeout error. Requesting https://api.bitfinex.com/v1/credits
    Caught API Error 520: The web server reported a bad gateway or gateway timeout error. Requesting https://api.bitfinex.com/v1/credits reading from exchange API, ignoring.

Which I'm guessing also contributes.

This isn't a huge deal and doesn't seem to be impacting the bot very much but I thought I'd bring it up. May just be my end.

UPDATE: this also happens with my Raspi

**Comment by laxdog** [comment]
Are you running the latest source @chriscrutt ? I put a fix in for this recently.
