### ISSUE TITLE
Using Docker on AWS issues

### ISSUE THREAD

**Issue by utdrmac** [BitBotFactory/poloniexlendingbot#542]
I'm attempting to use the bot by deploying in AWS Elastic Beanstalk. You can create a zip of the main directory and upload that as a deployment. EB then reads the Dockerfile and creates a regular docker instance.

The current issue surrounds the `VOLUME /data` part. I'm no expert with Docker so I'm explaining here in hopes that someone else knows what needs to be set.

`/data` is being created in my Docker. But it is empty. The default.cfg does not get copied into that folder so initial start failed complaining of a missing default.cfg. I modified the `CMD` to look in same directory and that started things up.

But now the issue is with botlog.json. There are two `ln -s` commands ran to symlink `/data/market_data` and `/data/log/` but there must be a part missing because, as above, the `/data` is currently empty.

Maybe there also needs to be a `COPY default.cfg /data/default.cfg`?

**Comment by utdrmac** [comment]
Here was the Dockerfile that worked for me. Notice the re-order of VOLUME. I think having it before the RUN command was somehow mounting over the directory and thus it was empty.

```
FROM python:2.7-slim
LABEL "project.home"="https://github.com/BitBotFactory/poloniexlendingbot"

#
# Build: docker build -t <your_id>/pololendingbot .
# Run: docker run -d -v /pololendingbot_data:/data -p 8000:8000 <your_id>/pololendingbot
#

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r ./requirements.txt

COPY . .

RUN mkdir -p /data/log /data/conf /data/market_data; \
    ln -s /data/log/botlog.json www/botlog.json; \
    rm -rf market_data; ln -s /data/market_data market_data

VOLUME /data

EXPOSE 80

CMD ["python", "lendingbot.py", "-cfg", "default.cfg"]
```

**Comment by laxdog** [comment]
Can you try the docker-compose file instead? I know it works as I updated it recently. You can also run multiple bots (and exchanges) from that file. It all gets automagically put behind an ngnix too.

**Comment by utdrmac** [comment]
The AWS GUI doesn't support docker-compose. It only reads Dockerfile, either uploaded directly or contained in a zip with other app files. I've read that you can use compose files on command-line from within another EC2 instance, but that requires spinning up an instance, ssh'ing, installing tools, etc, etc. I was looking for a simple, 3-click deployment.

Have you pushed/built an official docker image to docker hub? I'm not sure how API keys/secrets would be set though.
