### ISSUE TITLE
Maxloansize?

### ISSUE THREAD

**Issue by chriscrutt** [BitBotFactory/poloniexlendingbot#557]
discussion/enhancement

is/could there be a way to only let the bot loan out a certain amount per day, or around a certain amount per day?

for example if I have $120, and I only want to loan 50% of total balance per day, or only want to lend out $50 a day, or what have you.

This would enable users to span out their loans so if it spikes on a day you've already loaned your money, you can still catch the spike. example: first day USD for 0.03% next day at 0.2%

This could also include options such as (lets say I wanted to loan out $60 daily) (FYI $50 is the lowest loan amount on Bitfinex so that's what I'm using here)

if (USD_available < 50) {
do nothing (nothing you can do here lol)
} else if (USD_available <= 60) {
loan all USD
} else if (USD_available - 60 < 50) {
loan all USD
} else {
loan 60
}

this makes it so if there's less than $50, do nothing;
less than 60, loan all;
if all available (non lent) USD, minus 60, is less than 50, loan all;
if all else is false, that means there's at least $110 in the account and you can go ahead and loan $60

this is if we wanted to use percents (40% for this)

if (USD_available < 50) {
do nothing (nothing you can do here lol)
} else if (USD_available <= 40 %_of_total) {
loan all USD
} else if (USD_available - 40 %_of_total < 50) {
loan all USD
} else {
loan 40 %_of_total
}

just the basics, we/y'all can add to it or select what you like from it, or better yet it's already implemented and I just overlooked it (and typed all this out making myself look stupid)

I hope y'all can take at least one idea from this.

Thanks!

**Comment by rnevet** [comment]
There is a feature that should allow you to do this:
http://poloniexlendingbot.readthedocs.io/en/latest/configuration.html#max-to-be-lent

**Comment by chriscrutt** [comment]
"If the remainder (after subtracting maxpercenttolend‘s value) in a coin’s balance is less than minloansize, then the remainder will be lent anyway. Otherwise, the coins would go to waste since you can’t lend under minloansize"

perfect...

now for the other option, is there a way to set a `maxtolend` as a USD value.

for example Bitfinex has a minimum loan amount of $50 or an equivalent to $50. Could/is there a way to lend a maximum of $50 worth of BTC. so one day your maximum might be 0.01 BTC and the next it may be 0.0095 BTC?

**Comment by rnevet** [comment]
No.

**Comment by rnevet** [comment]
Issue resolved? :)

**Comment by chriscrutt** [comment]
lol I suppose so... I tried to figure out how to get current BTC to USD price (from poloniex and bitfinex respectively) and set maxtolend to BTCUSDPrice/$50 but I couldn't figure it out.

I'll go ahead and close
