### ISSUE TITLE
Email Enhancement

### ISSUE THREAD

**Issue by mmoroni75** [BitBotFactory/poloniexlendingbot#560]
Some email providers have a "sender" my@email.com and a account user "my3433" that must be userd in order to send the email.
in the default.cfg there is no space for the "user".
Is it possible to modify the bot in order to add this feature?

**Comment by utdrmac** [comment]
@mmoroni75 Have you attempted to put "my3433" as `email_login_address`?

**Comment by laxdog** [comment]
@mmoroni75 I'm closing this if I don't hear back from you shortly.
