### ISSUE TITLE
Unknown currency

### ISSUE THREAD

**Issue by mike4001** [BitBotFactory/poloniexlendingbot#568]
Hi

I am getting this Error every minute since a 4-5 hours
```
Error API Error 400: {"message":"Unknown currency"} Requesting https://api.bitfinex.com/v1/lendbook/BTG?limit_asks=100&limit_bids=100
```
BTG seems to refer to Bitcoin Gold, but I didn't change anything in my config file for weeks and don't know how the bot could know about the "BTG" ticker ???

**Comment by Nmaw** [comment]
It is new coins on Bitfinex. If you have some BTC, after fork you also have some BTG.

**Comment by mike4001** [comment]
Thanks for the info but please read my post ...

My bot is doing nothing but showing me this Error message every minute

**Comment by MoonMaker** [comment]
Hi,

please have a look to Added Blacklist Option #570

**Comment by utdrmac** [comment]
I don't have BTG listed in `all_currencies` so why is the bot bothering to check this coin?

`all_currencies = USD,BTC,ETH,BCH,ETC`

**Comment by mike4001** [comment]
#570 fixes the issue.

And I also don't know why @utdrmac - I also don't have it listed in all_currencies.

**Comment by chfast** [comment]
Quick workaround: login to Bitfinex and move BTG from funding wallet to exchange wallet.

**Comment by utdrmac** [comment]
@chfast That isn't a valid workaround. The API call being made is public API. It has nothing to do with what you have in your individual wallets. Bitfinex isn't allowing lending of BTG at this time. That's why this error exists in the first place.

**Comment by chfast** [comment]
All workarounds that works are valid. And this one works.

The bot will not ask about BTG if you have 0 to lend.

**Comment by utdrmac** [comment]
The API error noted in this bug report has absolutely nothing to do with balances in your personal accounts. Thus, moving coins around inside your own account/wallets/etc will make no difference and this API call will continue to fail.

**Comment by utdrmac** [comment]
I acknowledge that by moving the coins around, the bot won't "see" a balance of BTG and will therefore not make this API call against lendingbook API in the first place. For that reason, it is a workaround but doesn't fix the original issue.

**Comment by rnevet** [comment]
Actually Bitfinex letting you have Lending balances that you can't lend is just weird... it is the the cause of this issue and moving the fund off the half baked Lending account is a valid temporary solution till Bitfinex either enable BTG lending or not.  

Otherwise the white list check that in #570 is also a valid code solution.
