### ISSUE TITLE
Docker build fail on RaspberryPi

### ISSUE THREAD

**Issue by utdrmac** [BitBotFactory/poloniexlendingbot#574]
Attached log. This was a fresh download of Hypriot's Docker for RaspberryPi which includes the latest docker version. Maybe the base docker image is missing some compile tools/libraries?

[docker_fail_log.txt](https://github.com/BitBotFactory/poloniexlendingbot/files/1425324/docker_fail_log.txt)

**Comment by laxdog** [comment]
Yea, I've seen this before on some NAS devices. 

It could be worked around, but really the best solution is for us to roll our own docker images that have everything pre-built. 

I've been toying with the idea anyway as it would drastically reduce startup time. 

If you really want to get it working you can add RUN or CMD commands before the pip stuff run. You probably need to install at the least gcc-g++, I'm not sure what distro or package manager it uses.

Ping me on Slack if you want to work through it.

**Comment by laxdog** [comment]
@utdrmac Can we close this, it's out of our control really.

**Comment by laxdog** [comment]
I've made a fix for this @utdrmac can you test it?
