### ISSUE TITLE
Question to xday

### ISSUE THREAD

**Issue by MoonMaker** [BitBotFactory/poloniexlendingbot#580]
Hello,

I would like to increase the max. lending days to 30 on bitfinex, when we have a very good rate like >= 0.1. Is this already possible with xdays or should I look for a new pr?

Cheers

Thomas

**Comment by rnevet** [comment]
already possible
http://poloniexlendingbot.readthedocs.io/en/latest/configuration.html#variable-loan-length

**Comment by MoonMaker** [comment]
Thanks, I will test it.
