### ISSUE TITLE
[Feature Idea] Loan Duration Tiers

### ISSUE THREAD

**Issue by CrossyFTW** [BitBotFactory/poloniexlendingbot#581]
A feature I would really love to see would be tiered loan durations. Currently, there is the ability to set a longer loan period if the rate is above a certain value.

However, if we could set multiple conditions that would allow users to optimize their returns. Eg:

If > 0.5%, then 10 days.
If > 0.75% then 20 days.
If > 2.0% then 60 days.

Hope this makes sense but happy to try again if it's not clear.

Also, being able to set loan duration at a coin level (rather than across all coins) might be handy.

Thanks!

**Comment by rnevet** [comment]
Did you see this:
http://poloniexlendingbot.readthedocs.io/en/latest/configuration.html#variable-loan-length
?

**Comment by CrossyFTW** [comment]
I did not! That's perfect, thanks!! Looks like its a new addition to the config file since my version. Sorry for missing it.
