### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Sbf93** [BitBotFactory/poloniexlendingbot#583]
I just downloaded the latest master.zip and tried to run it on Bitfinex. This is what I get:

```
Traceback (most recent call last):
  File "lendingbot.py", line 17, in <module>
    from modules.ExchangeApiFactory import ExchangeApiFactory
  File "...\poloniexlendingbot-master\modules\ExchangeApiFactory.py", line 6, in <module>
    from modules.Bitfinex import Bitfinex
  File "...\poloniexlendingbot-master\modules\Bitfinex.py", line 6, in <module>
    import requests
ImportError: No module named requests
```

Is this my fault or a valid problem?

**Comment by Sbf93** [comment]
Nevermind, I found the solution myself, I needed to run

`pip install -r requirements.txt`

I thought this step was optional regarding the documentation?

**Comment by rnevet** [comment]
It's optional if you install all requirements, feel free to offer improvement to the documentation (Make a Pull Request).
