### ISSUE TITLE
bot window closes immediately after start

### ISSUE THREAD

**Issue by Bonez0r** [BitBotFactory/poloniexlendingbot#586]
Yesterday i downloaded the latest poloniexbot-master zip. After editing the config file i double click on lendingbot.py and the window opens for a fraction of a second and then closes. There's some text in the window but it's gone too fast to read.  If i start the bot in a command prompt window with the command "python lendingbot.py" i get the following:

```
Traceback (most recent call last):
  File "lendingbot.py", line 17, in <module>
    from modules.ExchangeApiFactory import ExchangeApiFactory
  File "J:\temp\Bitcoin\poloniexlendingbot-master\modules\ExchangeApiFactory.py", line 6, in <module>
    from modules.Bitfinex import Bitfinex
  File "J:\temp\Bitcoin\poloniexlendingbot-master\modules\Bitfinex.py", line 6, in <module>
    import requests
ImportError: No module named requests
```

The older version i have works fine. I enter the same command in the old version and i get this:

```
Welcome to Poloniex Lending Bot
2017-12-03 20:45:17 Using custom mindailyrate 0.0200% for FCT

(etc... working as it should)
```

Am i doing something wrong? Am i supposed to use docker? According to the docs at https://poloniexlendingbot.readthedocs.io i should be able to start the bot the same way i always have.

I would also like to run a bot for Poloniex and one for Bitfinex at the same time.  Is this possible without docker? To be honest i'm no that much of a techie. Editing the config file is fine, but setting up docker looks rather intimidating.

**Comment by rnevet** [comment]
Update your dependencies.

**Comment by rnevet** [comment]
If you double click on a python file and it finishes (also with an error) the window will close, that's normal. Is the issue solved?

**Comment by Bonez0r** [comment]
Yes sorry, it's solved. I ran into problems when i installed the wrong Python version, but once i uninstalled both versions and re-installed the correct version i managed to install the required modules.
