### ISSUE TITLE
hello Can you solve this error?

### ISSUE THREAD

**Issue by Helloguys11** [BitBotFactory/poloniexlendingbot#587]

**Comment by utdrmac** [comment]
Do you have the ca-certificates package installed?

**Comment by Helloguys11** [comment]
> to utdmac /// I am not sure what you mean. Should I install it? is it free? where could I get?

**Comment by utdrmac** [comment]
ca-certificates is the base package for all linux-based OS that contains up to date root CA certificates. Since your bot is failing to recognize the certificate from poloniex, this tells me that you don't have the proper root certificates installed.

**Comment by utdrmac** [comment]
which OS are you using? use Google to search for how to update/install the package.

**Comment by Helloguys11** [comment]
to utdrmac : windows server 2016

**Comment by utdrmac** [comment]
Sorry. Can't assist. I don't do Windows. Are you running this inside docker or just Python on windows? Could be that your python installation is missing the certificates.

Says here that Python on windows doesn't use the Windows certificates. https://stackoverflow.com/a/42983111/1461007

**Comment by rnevet** [comment]
No details in issue? Reopen if needed.
