### ISSUE TITLE
Why no huobi pro?

### ISSUE THREAD

**Issue by chinarichman** [BitBotFactory/poloniexlendingbot#595]
I also need huobi data, please add it.
Thank you. ASAP

**Comment by rnevet** [comment]
What's huobi?  (and if you need it ASAP, code it.)

**Comment by rnevet** [comment]
Huobi pro doesn't support Lending as far as I can see.

**Comment by chinarichman** [comment]
Hi bro huobi pro support lending now.
 I think many people especially in China use you code trading on huobi.
Speaking of bounty could you please leave a gmail account or something we could talk about it in detail.

Thank you.

**Comment by rnevet** [comment]
Can you link to API documentation?

**Comment by chinarichman** [comment]
https://github.com/huobiapi/API_Docs_en/wiki

Here is the link, thanks.

2017-12-15 17:01 GMT+08:00 Raanan <notifications@github.com>:

**Comment by utdrmac** [comment]
@chinarichman There's no lending stuff in that API. Doesn't look like they do lending.
