### ISSUE TITLE
[Issue] Charts not updating

### ISSUE THREAD

**Issue by bkuhl** [BitBotFactory/poloniexlendingbot#604]
I had some loans pay out last night, but the charts are not updated to reflect that.  Refreshing the page or opening it in incognito mode doesn't resolve the issue.

**Comment by utdrmac** [comment]
@bkuhl Charts refresh on a 1-day (86400s) period. If you start the bot at 13:45 PST, they won't refresh until 13:45 PST the next day. This is done to save API calls. You can change this interval if you want in the config file:
```
[ACCOUNTSTATS]
ReportInterval=3600
```

**Comment by bkuhl** [comment]
Doh!  Thanks
