### ISSUE TITLE
[Feature] Ability to select graphs to display

### ISSUE THREAD

**Issue by smccloud** [BitBotFactory/poloniexlendingbot#605]
In the past I have loaned DOGE, XMR, LTC & BTC.  However, I am no longer loaning anything but DOGE & BTC.  I would love the ability to configure the bot not to display the graphs for XMR & LTC but this is currently not any option.

**Comment by Evanito** [comment]
https://github.com/BitBotFactory/poloniexlendingbot/blob/b6cf7079a3a283432e6d07bd7357e0ace676a7ea/www/lendingbot.js#L112

In this line add a check that the coin has any being actively lent

**Comment by Evanito** [comment]
@utdrmac is author of the Charts plugin

**Comment by utdrmac** [comment]
@tuberculo @AlexEremeenkov @smccloud Let me know if the recent patch works to your liking. It just grabs your active coins and only displays them on the charts.
