### ISSUE TITLE
Allow lending on Quoine

### ISSUE THREAD

**Issue by rnevet** [BitBotFactory/poloniexlendingbot#608]
Quoine exchange allows lending, it would be nice to have the bot supporting it as well.

API:
https://developers.quoine.com/v2#assets-lending

**Comment by HostFat** [comment]
Fees are high anyway :)

https://quoine.zendesk.com/hc/en-us/articles/218093878-Asset-Lending

50%

**Comment by rnevet** [comment]
Seems like the feature isn't active, thanks.  Reopen when relevant.
