### ISSUE TITLE
[Bitfinex] Error API Error 405

### ISSUE THREAD

**Issue by utdrmac** [BitBotFactory/poloniexlendingbot#619]
Ever since updating to latest HEAD (ce424469ee9c684d720be106f6dc1f57547d1544) I've been getting these on my console. Not sure if this is a bot issue or exchange issue. The error is not caught very nicely.

```
 Requesting https://api.bitfinex.com/v1/credits reading from exchange API, ignoring.
2018-03-21 07:31:59 Error API Error 405: <html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
 Requesting https://api.bitfinex.com/v1/credits
Caught API Error 405: <html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by rnevet** [comment]
I had those also today, seemed to be a temp issue as it's gone. 
Regarding "The error is not caught very nicely" it is caught and logged, don't see a need for a specific implementation for it as today was the first it popped up.

**Comment by utdrmac** [comment]
If it is caught correctly, why is there HTML output?

**Comment by rnevet** [comment]
@utdrmac 
You can see the error handling logic here, it just prints the exception message.
https://github.com/BitBotFactory/poloniexlendingbot/blob/master/lendingbot.py#L159

and here is the message generated for this case:
https://github.com/BitBotFactory/poloniexlendingbot/blob/fcd3fbb83797cb636a55b9059d8273b071c2beaa/modules/Bitfinex.py#L90
