### ISSUE TITLE
Error HTTP Error 500: Poloniex reports: 'Internal error'.

### ISSUE THREAD

**Issue by Sigri44** [BitBotFactory/poloniexlendingbot#624]
Hi,

Since 2 days, i have this error : 
Error HTTP Error 500: Internal Server Error Requesting returnActiveLoans. Poloniex reports: 'Internal error. Please try again.'

Can you help me ? I have reboot my docker image and the same error is after 12/24h the reboot.

Thank.

**Comment by Evanito** [comment]
Hello, 500 errors are caused by Poloniex and should go away after some duration of time.

Please make sure you are also running the most recent version of the bot.
