### ISSUE TITLE
Next stable release?

### ISSUE THREAD

**Issue by bkuhl** [BitBotFactory/poloniexlendingbot#627]
The last release was in October of 2015.  It has been quite some time and a lot has happened in this project since then.  Is there a target for the next release?

**Comment by rnevet** [comment]
I suggest using Master branch.

**Comment by bkuhl** [comment]
I could, but that doesn't answer my question.  Are there plans to version this and release change logs or continue down the path of only maintaining a master branch?

**Comment by Evanito** [comment]
Added a notice on the releases page that should explain our situation.

TLDR: we use github flow which guarantees master branch is the best source for updates
