### ISSUE TITLE
USDt (tether) lending on Bitfinex missing

### ISSUE THREAD

**Issue by nedis4** [BitBotFactory/poloniexlendingbot#656]
USDt lending doesn't seem supported by the bot. Can this be added? USD lending on Bitfinex works nice while USDt is being ignored by the bot. This is a shame because rates for tether is higher and this is a convenient deposit/withdrawal currency.

**Comment by texke** [comment]
Hey,
You can use the symbol UST, this is the Bitfinex Symbol for USDt.

**Comment by nedis4** [comment]
Thank you! Didn't find the right symbol 😅
