### ISSUE TITLE
Min daily rate to 0.0003

### ISSUE THREAD

**Issue by alns0dev** [BitBotFactory/poloniexlendingbot#663]
Apparently, the bot is not allowing for less than 0.001% of the min daily rate although the current market situation sits at 0.0003%; when updating the code to that rate is not able to run, can anyone give support?

Thanks!

**Comment by rnevet** [comment]
As the configuration says:
#Setting to 0.0031 is about 1% a year, not worth it.

**Comment by alns0dev** [comment]
> As the configuration says: #Setting to 0.0031 is about 1% a year, not worth it.

So given the current rates, it'd be impossible to use the bot? If it's less than 0.003 then I can't use it?

**Comment by rnevet** [comment]
No, you need to manually change the code in this line:
https://github.com/BitBotFactory/MikaLendingBot/blob/b59ab8709220b3be1481ca8949a80f944b05018e/modules/Lending.py#L70
and depending on your configuration maybe also in this line:
https://github.com/BitBotFactory/MikaLendingBot/blob/b59ab8709220b3be1481ca8949a80f944b05018e/modules/Lending.py#L271

you can see the 0.003 is set there as the lower limit for this config value.

**Comment by alns0dev** [comment]
> No, you need to manually change the code in this line:
> 
> https://github.com/BitBotFactory/MikaLendingBot/blob/b59ab8709220b3be1481ca8949a80f944b05018e/modules/Lending.py#L70
> 
> and depending on your configuration maybe also in this line:
> 
> https://github.com/BitBotFactory/MikaLendingBot/blob/b59ab8709220b3be1481ca8949a80f944b05018e/modules/Lending.py#L271
> 
> you can see the 0.003 is set there as the lower limit for this config value.

Thanks for your help, will try it out!
